/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.wealizh.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.client.event.RegisterRangeSelectItemModelPropertyEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.api.distmarker.Dist;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.SpawnEggItem;
import net.minecraft.world.item.Rarity;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.BlockItem;
import net.minecraft.resources.ResourceLocation;

import net.mcreator.wealizh.item.*;
import net.mcreator.wealizh.block.*;
import net.mcreator.wealizh.WealizhMod;

import java.util.function.Function;

public class WealizhModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(WealizhMod.MODID);
	public static final DeferredItem<Item> SILVER_INGOT;
	public static final DeferredItem<Item> SILVER_NUGGET;
	public static final DeferredItem<Item> SILVER_BLOCK;
	public static final DeferredItem<Item> RAW_SILVER;
	public static final DeferredItem<Item> WEALIZH_LCON;
	public static final DeferredItem<Item> QUALITATIVE_CHANGE;
	public static final DeferredItem<Item> SILVER_ORE;
	public static final DeferredItem<Item> DEEPSLATE_SILVER_ORE;
	public static final DeferredItem<Item> RAPID_QUALITATIVE_CHANGE_MACHINE;
	public static final DeferredItem<Item> STECKED_STONE_ALLOY_BLOCK;
	public static final DeferredItem<Item> STECKED_STONE_ALLOY;
	public static final DeferredItem<Item> PEBBLE;
	public static final DeferredItem<Item> FLUID_TANK_WATER;
	public static final DeferredItem<Item> WATER;
	public static final DeferredItem<Item> IRON_PLATE;
	public static final DeferredItem<Item> SILVER_PLATE;
	public static final DeferredItem<Item> EMPTY_SUBSTANCE_NUCLEUS;
	public static final DeferredItem<Item> QUALITATIVE_CHANGE_SUBSTANCE_NUCLEUS;
	public static final DeferredItem<Item> OVERPRESSURE_QUALITATIVE_CHANGE_SUBSTANCE_NUCLEUS;
	public static final DeferredItem<Item> STEEL_INGOT;
	public static final DeferredItem<Item> STEEL_BLOCK;
	public static final DeferredItem<Item> SLOWLNSRESPONSE_PERFORATED_PLATE;
	public static final DeferredItem<Item> STECKED_STONE_ALLOY_PLATE;
	public static final DeferredItem<Item> RAW_STEEL;
	public static final DeferredItem<Item> RAW_STEEL_BLOCK;
	public static final DeferredItem<Item> RAW_SILVER_BLOCK;
	public static final DeferredItem<Item> STEEL_NUGGET;
	public static final DeferredItem<Item> SMOOTH_STEEL_BLOCK;
	public static final DeferredItem<Item> WARNING_BLOCK;
	public static final DeferredItem<Item> MIXED_DYE_BLACK_YELLOW;
	public static final DeferredItem<Item> IRON_POWDER;
	public static final DeferredItem<Item> COPPER_POWDER;
	public static final DeferredItem<Item> GOLD_POWDER;
	public static final DeferredItem<Item> STONE_POWDER;
	public static final DeferredItem<Item> COAL_POWDER;
	public static final DeferredItem<Item> DIAMOND_POWDER;
	public static final DeferredItem<Item> EMERALD_POWDER;
	public static final DeferredItem<Item> LAPIS_LAZULI_POWDER;
	public static final DeferredItem<Item> CHARCOAL_POWDER;
	public static final DeferredItem<Item> QUARTZ_POWDER;
	public static final DeferredItem<Item> AMETHYST_POWDER;
	public static final DeferredItem<Item> SILVER_POWDER;
	public static final DeferredItem<Item> ZHEGNCOPPER_INGOT;
	public static final DeferredItem<Item> RAW_ZHEGNCOPPER;
	public static final DeferredItem<Item> ZHEGNCOPPER_ORE;
	public static final DeferredItem<Item> DEEPSLATE_ZHEGNCOPPER_ORE;
	public static final DeferredItem<Item> ZHEGNCOPPER_BLOCK;
	public static final DeferredItem<Item> RAW_ZHEGNCOPPER_BLOCK;
	public static final DeferredItem<Item> STECKED_STONE_ALLOY_POWDER;
	public static final DeferredItem<Item> STEEL_POWDER;
	public static final DeferredItem<Item> ZHEGNCOPPER_POWDER;
	public static final DeferredItem<Item> BRASS_INGOT;
	public static final DeferredItem<Item> BRASS_POWDER;
	public static final DeferredItem<Item> BRASS_BLOCK;
	public static final DeferredItem<Item> BRASS_NUGGET;
	public static final DeferredItem<Item> LIGNITE;
	public static final DeferredItem<Item> LIGNITE_POWDER;
	public static final DeferredItem<Item> LIGNITE_BLOCK;
	public static final DeferredItem<Item> LIGNITE_ORE;
	public static final DeferredItem<Item> DEEPSLATE_LIGNITE_ORE;
	public static final DeferredItem<Item> WAREHOUSE_BUCKET;
	public static final DeferredItem<Item> APPLE_WAREHOUSE_BUCKET;
	public static final DeferredItem<Item> GOLDEN_APPLE_WAREHOUSE_BUCKET;
	public static final DeferredItem<Item> POTATO_WAREHOUSE_BUCKET;
	public static final DeferredItem<Item> POISONOUS_POTATO_WAREHOUSE_BUCKET;
	public static final DeferredItem<Item> CARROT_WAREHOUSE_BUCKET;
	public static final DeferredItem<Item> GOLDEN_CARROT_WAREHOUSE_BUCKET;
	public static final DeferredItem<Item> BEETROOT_WAREHOUSE_BUCKET;
	public static final DeferredItem<Item> GLISTERING_MELON_SLICE_WAREHOUSE_BUCKET;
	public static final DeferredItem<Item> SWEET_BERRIES_WAREHOUSE_BUCKET;
	public static final DeferredItem<Item> GLOW_BERRIES_WAREHOUSE_BUCKET;
	public static final DeferredItem<Item> SUGAR_CANE_WAREHOUSE_BUCKET;
	public static final DeferredItem<Item> EGG_WAREHOUSE_BUCKET;
	public static final DeferredItem<Item> QUANTITATIVE_TRANSFORMATION_RECONSTRUCTOR;
	public static final DeferredItem<Item> STEEL_PLATE;
	public static final DeferredItem<Item> QUANTITATIVE_TRANSFORMATION_SUBSTANCE_NUCLEUS;
	public static final DeferredItem<Item> COPPER_NUGGET;
	public static final DeferredItem<Item> COMBUSTION_CHAMBER;
	public static final DeferredItem<Item> SILVER_PICKAXE;
	public static final DeferredItem<Item> SILVER_SWORD;
	public static final DeferredItem<Item> SILVER_AXE;
	public static final DeferredItem<Item> SILVER_SHOVEL;
	public static final DeferredItem<Item> SILVER_HOE;
	public static final DeferredItem<Item> ROCK_CRYSTAL;
	public static final DeferredItem<Item> ROCK_CRYSTAL_POWDER;
	public static final DeferredItem<Item> DEEPSLATE_ROCK_CRYSTAL_ORE;
	public static final DeferredItem<Item> ROCK_CRYSTAL_BLOCK;
	public static final DeferredItem<Item> HEAT_TRANSFER_PLATE;
	public static final DeferredItem<Item> COPPER_THREAD;
	public static final DeferredItem<Item> THERMAL_ENERGY_POWER_GENERATION_PANEL;
	public static final DeferredItem<Item> ALUMINUM_INGOT;
	public static final DeferredItem<Item> ALUMINUM_NUGGET;
	public static final DeferredItem<Item> ALUMINUM_POWDER;
	public static final DeferredItem<Item> ALUMINUM_PLATE;
	public static final DeferredItem<Item> ALUMINUM_THREAD;
	public static final DeferredItem<Item> IRON_THREAD;
	public static final DeferredItem<Item> GOLD_THREAD;
	public static final DeferredItem<Item> SILVER_THREAD;
	public static final DeferredItem<Item> STEEL_THREAD;
	public static final DeferredItem<Item> GOLD_PLATE;
	public static final DeferredItem<Item> COPPER_PLATE;
	public static final DeferredItem<Item> BUTTON_BATTERY;
	public static final DeferredItem<Item> ALUMINUM_STORAGE_BATTERY;
	public static final DeferredItem<Item> ALUMINUM_BLOCK;
	public static final DeferredItem<Item> ALUMINUM_ORE;
	public static final DeferredItem<Item> DEEPSLATE_ALUMINUM_ORE;
	public static final DeferredItem<Item> RAW_ALUMINUM;
	public static final DeferredItem<Item> RAW_ALUMINUM_BLOCK;
	public static final DeferredItem<Item> FLUID_TANK_LAVA;
	public static final DeferredItem<Item> LAVA;
	public static final DeferredItem<Item> CASING_THERMAL_ENERGY_POWER_GENERATION_PANEL;
	public static final DeferredItem<Item> HAND_INTERACTION;
	public static final DeferredItem<Item> WRENCH;
	public static final DeferredItem<Item> CRASHER;
	public static final DeferredItem<Item> PYRITE_CUBE;
	public static final DeferredItem<Item> PYRITE_POWDER;
	public static final DeferredItem<Item> PYRITE_BLOCK;
	public static final DeferredItem<Item> PYRITE_ORE;
	public static final DeferredItem<Item> DEEPSLATE_PYRITE_ORE;
	public static final DeferredItem<Item> EMPTY_BUTTON_BATTERY;
	public static final DeferredItem<Item> ELECTRICITY;
	public static final DeferredItem<Item> BATTERY;
	public static final DeferredItem<Item> EMPTY_BATTERY;
	public static final DeferredItem<Item> PRAISE_FOR_THE_COMBUSTION_CHAMBER;
	public static final DeferredItem<Item> STORAGE_BATTERY;
	public static final DeferredItem<Item> COBALTIZED_GLASS;
	public static final DeferredItem<Item> COBALTIZED_SAND;
	public static final DeferredItem<Item> TEMPERED_GLASS;
	public static final DeferredItem<Item> COBALTIZED_GLASS_PANE;
	public static final DeferredItem<Item> TEMPERED_GLASS_PANE;
	public static final DeferredItem<Item> FUEL_TANK_SOUL_FIRE_CATALYST;
	public static final DeferredItem<Item> INSULATION_HOSE;
	public static final DeferredItem<Item> INSULATION_BOARD;
	public static final DeferredItem<Item> COPPER_CORE_BATTERY;
	public static final DeferredItem<Item> EMPTY_COPPER_CORE_BATTERY;
	public static final DeferredItem<Item> INFINITE_BATTERY;
	public static final DeferredItem<Item> MIU_POLYMER_BLOCK;
	public static final DeferredItem<Item> URANIUM_INGOT;
	public static final DeferredItem<Item> RAW_URANIUM;
	public static final DeferredItem<Item> URANIUM_POWDER;
	public static final DeferredItem<Item> INFINITE_STORAGE_BATTERY;
	public static final DeferredItem<Item> URANIUM_BLOCK;
	public static final DeferredItem<Item> RAW_URANIUM_BLOCK;
	public static final DeferredItem<Item> URANIUM_ORE;
	public static final DeferredItem<Item> DEEPSLATE_URANIUM_ORE;
	public static final DeferredItem<Item> ALUMINUM_COPPER_ALLOY_INGOT;
	public static final DeferredItem<Item> ALUMINUM_COPPER_ALLOY_POWDER;
	public static final DeferredItem<Item> ALUMINUM_COPPER_ALLOY_PLATE;
	public static final DeferredItem<Item> ALUMINUM_COPPER_ALLOY_BLOCK;
	public static final DeferredItem<Item> ALUMINUM_COPPER_ALLOY_BATTERY;
	public static final DeferredItem<Item> EMPTY_ALUMINUM_COPPER_ALLOY_BATTERY;
	public static final DeferredItem<Item> ALUMINUM_COPPER_ALLOY_STORAGE_BATTERY;
	public static final DeferredItem<Item> HAND_CRANKED_GENERATOR;
	public static final DeferredItem<Item> ROCKER;
	public static final DeferredItem<Item> GLASS_FRAGMENTS;
	public static final DeferredItem<Item> ASSEMBLY_TYPE_CONTROL_CONSOLE;
	public static final DeferredItem<Item> STEEL_BOX;
	public static final DeferredItem<Item> STEEL_PIPE;
	public static final DeferredItem<Item> REBAR;
	public static final DeferredItem<Item> LOW_LEVEL_CHIPS;
	public static final DeferredItem<Item> COPPER_CABLE;
	public static final DeferredItem<Item> YELLOW_CAKE;
	public static final DeferredItem<Item> BOLT_IRON_BLOCK;
	public static final DeferredItem<Item> SHALE;
	public static final DeferredItem<Item> EXPOSURE_TO_RADIATION;
	public static final DeferredItem<Item> DETONATOR;
	public static final DeferredItem<Item> DETONATOR_BLOCK;
	public static final DeferredItem<Item> ASSEMBLY_ROOM;
	public static final DeferredItem<Item> VOLTAGE_REGULATOR;
	public static final DeferredItem<Item> POWER_BOOSTER_UNIT;
	public static final DeferredItem<Item> COMPONENT_HOUSING_GOLD;
	public static final DeferredItem<Item> CLOCK_COMPONENT;
	public static final DeferredItem<Item> STEEL_FRAME;
	public static final DeferredItem<Item> STEEL_SHAFT;
	public static final DeferredItem<Item> STRANGE_CLOCK;
	public static final DeferredItem<Item> GEAR;
	public static final DeferredItem<Item> PEELING_SUGAR_CANE;
	public static final DeferredItem<Item> SUGAR_CANE_RESIDUE;
	public static final DeferredItem<Item> TRANSFORMATION;
	public static final DeferredItem<Item> EATING;
	public static final DeferredItem<Item> TOXIC;
	public static final DeferredItem<Item> COAL_DUST_LCON;
	public static final DeferredItem<Item> RADIOACTIVITY;
	public static final DeferredItem<Item> RECTANGULAR_AND_SQUARE_SHAPED_PYRITE_LCON;
	public static final DeferredItem<Item> GRAPHITE;
	public static final DeferredItem<Item> GRAPHITE_POWDER;
	public static final DeferredItem<Item> GRAPHITE_BLOCK;
	public static final DeferredItem<Item> GRAPHITE_ORE;
	public static final DeferredItem<Item> DEEPSLATE_GRAPHITE_ORE;
	public static final DeferredItem<Item> LEAD_INGOT;
	public static final DeferredItem<Item> RAW_LEAD;
	public static final DeferredItem<Item> LEAD_POWDER;
	public static final DeferredItem<Item> RAW_LEAD_BLOCK;
	public static final DeferredItem<Item> LEAD_ORE;
	public static final DeferredItem<Item> DEEPSLATE_LEAD_ORE;
	public static final DeferredItem<Item> GRAPHITELEAD_INGOT;
	public static final DeferredItem<Item> GRAPHITELEAD_POWDER;
	public static final DeferredItem<Item> GRAPHITELEAD_PLATE;
	public static final DeferredItem<Item> LEAD_PLATE;
	public static final DeferredItem<Item> GRAPHITELEAD_BLOCK;
	public static final DeferredItem<Item> LEAD_BLOCK;
	public static final DeferredItem<Item> QUICKLY_SHUT_OFF_THE_ENGINE_LCON;
	public static final DeferredItem<Item> QUICKLY_SHUT_OFF_THE_ENGINE_BUT_IT_IS_THE_SOUL_VERSION_LCON;
	public static final DeferredItem<Item> AN_APPLE_A_DAY_KEEPS_THE_DOCTOR_AWAY_LCON;
	public static final DeferredItem<Item> SALT;
	public static final DeferredItem<Item> FLINT_POWDER;
	public static final DeferredItem<Item> FLINT_BLOCK;
	public static final DeferredItem<Item> GLASS_SHARDS;
	public static final DeferredItem<Item> SOAKING;
	public static final DeferredItem<Item> GEAR_ASSEMBLY;
	public static final DeferredItem<Item> SMALL_GEAR;
	public static final DeferredItem<Item> LINGUAN_COBALT;
	public static final DeferredItem<Item> PEAT;
	public static final DeferredItem<Item> PEAT_BLOCK;
	public static final DeferredItem<Item> TURN_THE_CRANK_UNTIL_YOU_GET_TIRED_THEN_JUST_KEEP_ON_ENDURING_IT_ICON;
	public static final DeferredItem<Item> KILN;
	public static final DeferredItem<Item> SCHRODINGER;
	public static final DeferredItem<Item> SCHRODINGER_BLOCK;
	public static final DeferredItem<Item> BURN;
	public static final DeferredItem<Item> SOUL_BURN;
	public static final DeferredItem<Item> CRUSHER;
	public static final DeferredItem<Item> COMPOSITE_GUNPOWDER;
	public static final DeferredItem<Item> WIRING_LEAD;
	public static final DeferredItem<Item> IRON_GEAR_BLADE;
	public static final DeferredItem<Item> COPPER_GEAR_BLADE;
	public static final DeferredItem<Item> SILVER_GEAR_BLADE;
	public static final DeferredItem<Item> STEEL_GEAR_BLADE;
	public static final DeferredItem<Item> NETHERITE_POWDER;
	public static final DeferredItem<Item> NETHERITE_GEAR_BLADE;
	public static final DeferredItem<Item> NETHERITE_NUGGET;
	public static final DeferredItem<Item> REDSTONE_CRYSTAL;
	public static final DeferredItem<Item> RAW_REDSTONE_CRYSTAL;
	public static final DeferredItem<Item> RAW_REDSTONE_CRYSTAL_BLOCK;
	public static final DeferredItem<Item> REDSTONE_CRYSTAL_BLOCK;
	public static final DeferredItem<Item> PRESSING_MACHINE;
	public static final DeferredItem<Item> UNKNOWN;
	public static final DeferredItem<Item> PRESSING_STORAGE_ROOM;
	public static final DeferredItem<Item> RAW_REDSTONE;
	public static final DeferredItem<Item> RAW_REDSTONE_BLOCK;
	public static final DeferredItem<Item> TYPE_ITEM;
	public static final DeferredItem<Item> BY_PRODUCT;
	public static final DeferredItem<Item> STEEL_BILLETSMATERIAL;
	public static final DeferredItem<Item> POWDERED_BRAN_AND_MILLET_GRAINS_LCON;
	public static final DeferredItem<Item> SOLID_PLATE;
	public static final DeferredItem<Item> REDSTONE_WIRING_LEAD;
	public static final DeferredItem<Item> STEEL_SCAFFOLDING;
	public static final DeferredItem<Item> URANIUM_235_INGOT;
	public static final DeferredItem<Item> URANIUM_235_POWDER;
	public static final DeferredItem<Item> URANIUM_235_BLOCK;
	public static final DeferredItem<Item> ZINC_INGOT;
	public static final DeferredItem<Item> ZINC_POWDER;
	public static final DeferredItem<Item> ZINC_BLOCK;
	public static final DeferredItem<Item> ZINC_PLATE;
	public static final DeferredItem<Item> RAW_ZINC;
	public static final DeferredItem<Item> RAW_ZINC_BLOCK;
	public static final DeferredItem<Item> ZINC_ORE;
	public static final DeferredItem<Item> DEEPSLATE_ZINC_ORE;
	public static final DeferredItem<Item> DECAY;
	public static final DeferredItem<Item> FUNBELITY;
	public static final DeferredItem<Item> FUNBELITY_POWDER;
	public static final DeferredItem<Item> COMPRESSED_FUNBELITY;
	public static final DeferredItem<Item> FUNBELITY_BLOCK;
	public static final DeferredItem<Item> COMPRESSED_ALUMINUM_COPPER_ALLOY;
	public static final DeferredItem<Item> FUNBELITY_CYTOSPLASM;
	public static final DeferredItem<Item> COMPRESSOR;
	public static final DeferredItem<Item> COMPRESSION_CHAMBER;
	public static final DeferredItem<Item> STEEL_PISTON_GROUP;
	public static final DeferredItem<Item> GOLD_CABLE;
	public static final DeferredItem<Item> BRASS_CABLE;
	public static final DeferredItem<Item> BRASS_THREAD;
	public static final DeferredItem<Item> PLACER;
	public static final DeferredItem<Item> IRON_BILLETSMATERIAL;
	public static final DeferredItem<Item> DISCHARGE_BOX;
	public static final DeferredItem<Item> EXPERIENCE_PARTICLE;
	public static final DeferredItem<Item> EXPERIENCE_NUGGET;
	public static final DeferredItem<Item> EXPERIENCE_CUBE_NUGGET;
	public static final DeferredItem<Item> EXPERIENCE_ABSORBER;
	public static final DeferredItem<Item> EXPERIENCE_SOLID_CUBE;
	public static final DeferredItem<Item> EXPERIENCE_BLOCK;
	public static final DeferredItem<Item> SOLID_EXPERIENCE;
	public static final DeferredItem<Item> EXPERIENCE_RELEASE_DEVICE;
	public static final DeferredItem<Item> REMOTE_STARTER;
	public static final DeferredItem<Item> BUZZER;
	public static final DeferredItem<Item> NEUTRON_FISSION_GENERATOR_HONESILVER;
	public static final DeferredItem<Item> HONESILVER_BLOCK;
	public static final DeferredItem<Item> RAW_HONESILVER_BLOCK;
	public static final DeferredItem<Item> NETHER_HONESILVER_ORE;
	public static final DeferredItem<Item> HONESILVER_INGOT;
	public static final DeferredItem<Item> RAW_HONESILVER;
	public static final DeferredItem<Item> HONESILVER_POWDER;
	public static final DeferredItem<Item> DIED_GRASS_BLOCK;
	public static final DeferredItem<Item> GEIGER_COUNTER;
	public static final DeferredItem<Item> GEIGER_TUBE;
	public static final DeferredItem<Item> DECAYED_LOG;
	public static final DeferredItem<Item> CRACKED_BRICKS;
	public static final DeferredItem<Item> CENTRIFUGE;
	public static final DeferredItem<Item> CENTRIFUGE_AROUND_PIPE;
	public static final DeferredItem<Item> GAS_TANK_HELIUM_GAS;
	public static final DeferredItem<Item> FUNBICOBALT_BLOCK;
	public static final DeferredItem<Item> DECAYED_FUNBICOBALT_BLOCK;
	public static final DeferredItem<Item> PURE_FUNBICOBALT_BLOCK;
	public static final DeferredItem<Item> COBALT_BLOCK;
	public static final DeferredItem<Item> FUNBICOBALT;
	public static final DeferredItem<Item> DECAYED_FUNBICOBALT;
	public static final DeferredItem<Item> FUNBICOBALT_POWDER;
	public static final DeferredItem<Item> DECAYED_FUNBICOBALT_POWDER;
	public static final DeferredItem<Item> COBALT_INGOT;
	public static final DeferredItem<Item> COMPRESSED_FUNBICOBALT;
	public static final DeferredItem<Item> COMPRESSED_DECAYED_FUNBICOBALT;
	public static final DeferredItem<Item> PURE_FUNBICOBALT;
	public static final DeferredItem<Item> PURE_FUNBICOBALT_POWDER;
	public static final DeferredItem<Item> COBALT_POWDER;
	public static final DeferredItem<Item> DEEPSLATE_FUNBICOBALT_ORE;
	public static final DeferredItem<Item> GERMINATION;
	public static final DeferredItem<Item> LANGUAGE_TESTER;
	public static final DeferredItem<Item> HUMUS;
	public static final DeferredItem<Item> HUMUS_WAREHOUSE_BUCKET;
	public static final DeferredItem<Item> POLLUTION_SOURCE_SPAWN_EGG;
	public static final DeferredItem<Item> FUNBIELUMITUO;
	public static final DeferredItem<Item> FUNBIELUCURTUO;
	public static final DeferredItem<Item> LITYTIUM_INGOT;
	public static final DeferredItem<Item> LITYTIUM_POWDER;
	public static final DeferredItem<Item> LITYTIUM_BLOCK;
	public static final DeferredItem<Item> HELIUM_GAS;
	public static final DeferredItem<Item> RED_COPPER_POWDER;
	public static final DeferredItem<Item> RED_COPPER_NUGGET;
	public static final DeferredItem<Item> RED_COPPER_THREAD;
	public static final DeferredItem<Item> RED_COPPER_CABLE;
	public static final DeferredItem<Item> RED_COPPER_PLATE;
	public static final DeferredItem<Item> RED_COPPER_INGOT;
	public static final DeferredItem<Item> RED_COPPER_BLOCK;
	public static final DeferredItem<Item> COPPER_COIL;
	public static final DeferredItem<Item> RED_COPPER_COIL;
	public static final DeferredItem<Item> COPPER_STORAGE_BARREL;
	public static final DeferredItem<Item> IRON_STORAGE_BARREL;
	public static final DeferredItem<Item> A_PINCH_PURE_FUNBICOBALT_POWDER;
	public static final DeferredItem<Item> A_PINCH_FUNBELITY_POWDER;
	public static final DeferredItem<Item> A_PINCH_FUNBELITY_CYTOSPLASM;
	public static final DeferredItem<Item> ELECTRIC_MOTOR;
	public static final DeferredItem<Item> URANIUM_HEXAFLUORIDE;
	public static final DeferredItem<Item> GAS_TANK_URANIUM_HEXAFLUORIDE;
	public static final DeferredItem<Item> FLUORINE_GAS;
	public static final DeferredItem<Item> GAS_TANK_FLUORINE_GAS;
	public static final DeferredItem<Item> CONCENTRATION_URANIUM_HEXAFLUORIDE;
	public static final DeferredItem<Item> GAS_TANK_CONCENTRATION_URANIUM_HEXAFLUORIDE;
	public static final DeferredItem<Item> DEPLETED_URANIUM_HEXAFLUORIDE;
	public static final DeferredItem<Item> GAS_TANK_DEPLETED_URANIUM_HEXAFLUORIDE;
	public static final DeferredItem<Item> WIRE;
	public static final DeferredItem<Item> PIPE;
	public static final DeferredItem<Item> BARRELREVOLVING_WHEEL;
	public static final DeferredItem<Item> INFINITE_STORAGE_BARREL;
	public static final DeferredItem<Item> INFINITE_HOLD_STORAGE_TANK;
	public static final DeferredItem<Item> FIREPROOF_PAPER;
	public static final DeferredItem<Item> GRASS_FIBERS;
	public static final DeferredItem<Item> ROPE;
	public static final DeferredItem<Item> LAYER_COVERS_PLATE;
	public static final DeferredItem<Item> EMPTY;
	public static final DeferredItem<Item> PLANNING_PAPER_ELECTRICITY_BAR;
	public static final DeferredItem<Item> CREATIVE_PLANNING_PAPER_NBT;
	public static final DeferredItem<Item> PLANNING_PAPER_EMPTY;
	public static final DeferredItem<Item> PLANNING_PAPER_LIQUID_PIPE;
	public static final DeferredItem<Item> CONCENTRATED_WIRE;
	public static final DeferredItem<Item> CONCENTRATED_PIPE;
	public static final DeferredItem<Item> UNIDIRECTIONAL_WIRE_VALVE;
	public static final DeferredItem<Item> UNIDIRECTIONAL_PIPE_VALVE;
	public static final DeferredItem<Item> MEOW_TITANIUM_INGOT;
	public static final DeferredItem<Item> TITANIUM_INGOT;
	public static final DeferredItem<Item> TITANIUM_POWDER;
	public static final DeferredItem<Item> RAW_TITANIUM;
	public static final DeferredItem<Item> TITANIUM_BLOCK;
	public static final DeferredItem<Item> RAW_TITANIUM_BLOCK;
	public static final DeferredItem<Item> TITANIUM_ORE;
	public static final DeferredItem<Item> DEEPSLATE_TITANIUM_ORE;
	public static final DeferredItem<Item> TITANIUM_NUGGET;
	public static final DeferredItem<Item> TITANIUM_PLATE;
	public static final DeferredItem<Item> HANZESH_CUBE_CRYSTAL;
	public static final DeferredItem<Item> INDUSTRIAL_FURNACE_WALL;
	public static final DeferredItem<Item> PETRIFIED_FORGING_TEMPLATE;
	public static final DeferredItem<Item> QUARTZ_ORE;
	public static final DeferredItem<Item> DEEPSTALE_QUARTZ_ORE;
	public static final DeferredItem<Item> SULFUR_POWDER;
	public static final DeferredItem<Item> SULFUR_ORE;
	public static final DeferredItem<Item> DEEPSLATE_SULFUR_ORE;
	public static final DeferredItem<Item> SALTPETER;
	public static final DeferredItem<Item> SALTPETER_POWDER;
	public static final DeferredItem<Item> SALTPETER_BLOCK;
	public static final DeferredItem<Item> SALTPETER_ORE;
	public static final DeferredItem<Item> DEEPSLATE_SALTPETER_ORE;
	public static final DeferredItem<Item> TITANIUM_STORAGE_BARREL;
	public static final DeferredItem<Item> PLANNING_PAPER_CONCENTRATED_ASSIGN_PRIORITIES;
	public static final DeferredItem<Item> NUCLEAR_BOMB;
	public static final DeferredItem<Item> URANIUM_FILLED_BOMB;
	public static final DeferredItem<Item> A_PINCH_BRASS_POWDER;
	public static final DeferredItem<Item> A_PINCH_HONESILVER_POWDER;
	public static final DeferredItem<Item> URANIUM_235_NUGGET;
	public static final DeferredItem<Item> URANIUM_235_BILLETSMATERIAL;
	public static final DeferredItem<Item> CHARRED_STONE;
	public static final DeferredItem<Item> PLANNING_PAPER_TRANSMISSION_VOLUME;
	public static final DeferredItem<Item> ELECTRIC_LAMP;
	public static final DeferredItem<Item> ENCHANTED_GOLDEN_APPLE_WAREHOUSE_BUCKET;
	public static final DeferredItem<Item> CHARRED_STONE_SLAB;
	public static final DeferredItem<Item> CHARRED_STONE_STAIR;
	public static final DeferredItem<Item> CHARRED_STONE_WALL;
	public static final DeferredItem<Item> CHARCOALIZED_LOG;
	public static final DeferredItem<Item> CHARCOALIZED_PLANKS;
	public static final DeferredItem<Item> CHARCOALIZED_PLANKS_SLAB;
	public static final DeferredItem<Item> CHARCOALIZED_PLANKS_STAIR;
	public static final DeferredItem<Item> CHARCOALIZED_PLANKS_FENCE;
	public static final DeferredItem<Item> CHARCOALIZED_PLANKS_FENCE_GATE;
	public static final DeferredItem<Item> LOGISTICS_PIPE;
	public static final DeferredItem<Item> CONCENTRATED_LOGISTICS_PIPE;
	public static final DeferredItem<Item> ARGON_GAS;
	public static final DeferredItem<Item> GAS_TANK_ARGON_GAS;
	public static final DeferredItem<Item> TUNGSTEN_INGOT;
	public static final DeferredItem<Item> TUNGSTEN_POWDER;
	public static final DeferredItem<Item> TUNGSTEN_NUGGET;
	public static final DeferredItem<Item> TUNGSTEN_PLATE;
	public static final DeferredItem<Item> TUNGSTEN_THREAD;
	public static final DeferredItem<Item> RAW_TUNGSTEN;
	public static final DeferredItem<Item> TUNGSTEN_BLOCK;
	public static final DeferredItem<Item> RAW_TUNGSTEN_BLOCK;
	public static final DeferredItem<Item> TUNGSTEN_ORE;
	public static final DeferredItem<Item> DEEPSLATE_TUNGSTEN_ORE;
	public static final DeferredItem<Item> INCANDESCENT_LIGHT_BULB;
	public static final DeferredItem<Item> ANEMENROUNZE;
	public static final DeferredItem<Item> OXYGEN;
	public static final DeferredItem<Item> GAS_TANK_OXYGEN;
	public static final DeferredItem<Item> PLANNING_PAPER_REDSTONE_LOCK;
	public static final DeferredItem<Item> TEMPORARY_BLOCK;
	public static final DeferredItem<Item> CARBON_DIOXIDE;
	public static final DeferredItem<Item> GAS_TANK_CARBON_DIOXIDE;
	public static final DeferredItem<Item> NEON_GAS;
	public static final DeferredItem<Item> GAS_TANK_NEON_GAS;
	public static final DeferredItem<Item> FLUID_TANK_EMPTY;
	public static final DeferredItem<Item> GAS_TANK_EMPTY;
	public static final DeferredItem<Item> FUEL_TANK_EMPTY;
	public static final DeferredItem<Item> NICKEL_INGOT;
	public static final DeferredItem<Item> NICKEL_NUGGET;
	public static final DeferredItem<Item> RAW_NICKEL;
	public static final DeferredItem<Item> NICKEL_POWDER;
	public static final DeferredItem<Item> NICKEL_BLOCK;
	public static final DeferredItem<Item> RAW_NICKEL_BLOCK;
	public static final DeferredItem<Item> NICKEL_ORE;
	public static final DeferredItem<Item> DEEPSLATE_NICKEL_ORE;
	public static final DeferredItem<Item> NICKEL_THREAD;
	public static final DeferredItem<Item> NAN_SUBSTANCE;
	public static final DeferredItem<Item> CHROMIUM_INGOT;
	public static final DeferredItem<Item> CHROMIUM_NUGGET;
	public static final DeferredItem<Item> CHROMIUM_POWDER;
	public static final DeferredItem<Item> CHROMIUM_THREAD;
	public static final DeferredItem<Item> CHROMIUM_BLOCK;
	public static final DeferredItem<Item> RAW_CHROMIUM_BLOCK;
	public static final DeferredItem<Item> CHROMIUM_ORE;
	public static final DeferredItem<Item> DEEPSLATE_CHROMIUM_ORE;
	public static final DeferredItem<Item> RAW_CHROMIUM;
	public static final DeferredItem<Item> NICKEL_CHROMIUM_ALLOY_INGOT;
	public static final DeferredItem<Item> NICKEL_CHROMIUM_ALLOY_NUGGET;
	public static final DeferredItem<Item> NICKEL_CHROMIUM_ALLOY_POWDER;
	public static final DeferredItem<Item> NICKEL_CHROMIUM_ALLOY_THREAD;
	public static final DeferredItem<Item> NICKEL_CHROMIUM_ALLOY_COIL;
	public static final DeferredItem<Item> NICKEL_CHROMIUM_ALLOY_BLOCK;
	public static final DeferredItem<Item> ELECTRIC_HEATER;
	public static final DeferredItem<Item> AIR_SEPARATOR;
	public static final DeferredItem<Item> HYDROGEN;
	public static final DeferredItem<Item> GAS_TANK_HYDROGEN;
	public static final DeferredItem<Item> NITROGEN;
	public static final DeferredItem<Item> GAS_TANK_NITROGEN;
	public static final DeferredItem<Item> METHANE;
	public static final DeferredItem<Item> GAS_TANK_METHANE;
	public static final DeferredItem<Item> KRYPTON_GAS;
	public static final DeferredItem<Item> GAS_TANK_KRYPTON_GAS;
	public static final DeferredItem<Item> DINITROGEN_MONOXIDE;
	public static final DeferredItem<Item> GAS_TANK_DINITROGEN_MONOXIDE;
	public static final DeferredItem<Item> XENON_GAS;
	public static final DeferredItem<Item> GAS_TANK_XENON_GAS;
	public static final DeferredItem<Item> OZONE;
	public static final DeferredItem<Item> GAS_TANK_OZONE;
	public static final DeferredItem<Item> SLOT_OCCUPANCY_PLATE;
	public static final DeferredItem<Item> BLADE;
	public static final DeferredItem<Item> LUMP_SULFUR;
	public static final DeferredItem<Item> SULFUR;
	public static final DeferredItem<Item> LUMP_POTENT_SULFUR;
	public static final DeferredItem<Item> POTENT_SULFUR_POWDER;
	public static final DeferredItem<Item> POTENT_SULFUR;
	public static final DeferredItem<Item> BRICK_CHIMNEY;
	public static final DeferredItem<Item> IRON_SLAB;
	public static final DeferredItem<Item> BRICK_CHIMNEY_OPENING;
	public static final DeferredItem<Item> IRON_STAIR;
	public static final DeferredItem<Item> STEEL_SLAB;
	public static final DeferredItem<Item> STEEL_STAIR;
	public static final DeferredItem<Item> SMOOTH_STEEL_SLAB;
	public static final DeferredItem<Item> SMOOTH_STEEL_STAIR;
	public static final DeferredItem<Item> SMOOTH_IRON_BLOCK;
	public static final DeferredItem<Item> SMOOTH_IRON_STAIR;
	public static final DeferredItem<Item> SMOOTH_IRON_SLAB;
	public static final DeferredItem<Item> BOLT_IRON_STAIR;
	public static final DeferredItem<Item> BOLT_IRON_SLAB;
	public static final DeferredItem<Item> IRON_WALL;
	public static final DeferredItem<Item> SMOOTH_IRON_WALL;
	public static final DeferredItem<Item> BOLT_IRON_WALL;
	public static final DeferredItem<Item> STEEL_WALL;
	public static final DeferredItem<Item> SMOOTH_STEEL_WALL;
	public static final DeferredItem<Item> PRESSURE_MEASURING_PAPER_TUBE;
	public static final DeferredItem<Item> RADIOACTIVE_FALLOUT;
	public static final DeferredItem<Item> THE_COLD_WINTER_ICON;
	public static final DeferredItem<Item> DIED_SHORT_GRASS;
	public static final DeferredItem<Item> DIED_TALL_GRASS;
	public static final DeferredItem<Item> DIED_SHORT_GRASS_DESERT_DUST;
	public static final DeferredItem<Item> DIED_TALL_GRASS_DESERT_DUST;
	public static final DeferredItem<Item> STEEL_BEAM;
	public static final DeferredItem<Item> IRONL_SCAFFOLDING;
	public static final DeferredItem<Item> IRON_BEAM;
	public static final DeferredItem<Item> STUDIO_DOOR;
	public static final DeferredItem<Item> OLD_STUDIO_DOOR;
	public static final DeferredItem<Item> WAXED_STUDIO_DOOR;
	public static final DeferredItem<Item> MILK;
	public static final DeferredItem<Item> GLASS_BAFFLE_PLATE;
	public static final DeferredItem<Item> FLUID_TANK_MILK;
	public static final DeferredItem<Item> AMETHYST_BRICKS;
	public static final DeferredItem<Item> WHITE_CRYSTAL_SHARD;
	public static final DeferredItem<Item> WHITE_CRYSTAL_POWDER;
	public static final DeferredItem<Item> WHITE_CRYSTAL_BLOCK;
	public static final DeferredItem<Item> BUDDING_WHITE_CRYSTAL;
	public static final DeferredItem<Item> SMALL_WHITE_CRYSTAL_BUD;
	public static final DeferredItem<Item> MEDIUM_WHITE_CRYSTAL_BUD;
	public static final DeferredItem<Item> LARGE_WHITE_CRYSTAL_BUD;
	public static final DeferredItem<Item> WHITE_CRYSTAL_CLUSTER;
	public static final DeferredItem<Item> WHITE_CRYSTAL_BRICKS;
	public static final DeferredItem<Item> CHARRED_BEDROCK;
	public static final DeferredItem<Item> MOLTEN_HIGH_TEMPERATURE_SOLIDIFIED_SUBSTANCE;
	public static final DeferredItem<Item> MOLTEN_SAND_SOLIDIFICATION_SUBSTANCE;
	public static final DeferredItem<Item> TRINITITE;
	public static final DeferredItem<Item> TRINITITE_PANE;
	public static final DeferredItem<Item> DAWN_THE_TRUE_DAWN_ICON;
	static {
		SILVER_INGOT = register("silver_ingot", SilverIngotItem::new);
		SILVER_NUGGET = register("silver_nugget", SilverNuggetItem::new);
		SILVER_BLOCK = block(WealizhModBlocks.SILVER_BLOCK);
		RAW_SILVER = register("raw_silver", RawSilverItem::new);
		WEALIZH_LCON = register("wealizh_lcon", WealizhLconItem::new);
		QUALITATIVE_CHANGE = register("qualitative_change", QualitativeChangeLconItem::new);
		SILVER_ORE = block(WealizhModBlocks.SILVER_ORE);
		DEEPSLATE_SILVER_ORE = block(WealizhModBlocks.DEEPSLATE_SILVER_ORE);
		RAPID_QUALITATIVE_CHANGE_MACHINE = block(WealizhModBlocks.RAPID_QUALITATIVE_CHANGE_MACHINE);
		STECKED_STONE_ALLOY_BLOCK = block(WealizhModBlocks.STECKED_STONE_ALLOY_BLOCK);
		STECKED_STONE_ALLOY = register("stecked_stone_alloy", SteckedStoneAlloyItem::new);
		PEBBLE = register("pebble", PebbleItem::new);
		FLUID_TANK_WATER = register("fluid_tank_water", FluidTankWaterItem::new);
		WATER = register("water", WaterItem::new);
		IRON_PLATE = register("iron_plate", IronPlateItem::new);
		SILVER_PLATE = register("silver_plate", SilverPlateItem::new);
		EMPTY_SUBSTANCE_NUCLEUS = register("empty_substance_nucleus", EmptySubstanceNucleusItem::new);
		QUALITATIVE_CHANGE_SUBSTANCE_NUCLEUS = register("qualitative_change_substance_nucleus", QualitativeChangeSubstanceNucleusItem::new);
		OVERPRESSURE_QUALITATIVE_CHANGE_SUBSTANCE_NUCLEUS = register("overpressure_qualitative_change_substance_nucleus", OverpressureQualitativeChangeSubstanceNucleusItem::new);
		STEEL_INGOT = register("steel_ingot", SteelIngotItem::new);
		STEEL_BLOCK = block(WealizhModBlocks.STEEL_BLOCK);
		SLOWLNSRESPONSE_PERFORATED_PLATE = register("slowlnsresponse_perforated_plate", SlowlnsresponsePerforatedPlateItem::new);
		STECKED_STONE_ALLOY_PLATE = register("stecked_stone_alloy_plate", SteckedStoneAlloyPlateItem::new);
		RAW_STEEL = register("raw_steel", RawSteelItem::new);
		RAW_STEEL_BLOCK = block(WealizhModBlocks.RAW_STEEL_BLOCK);
		RAW_SILVER_BLOCK = block(WealizhModBlocks.RAW_SILVER_BLOCK);
		STEEL_NUGGET = register("steel_nugget", SteelNuggetItem::new);
		SMOOTH_STEEL_BLOCK = block(WealizhModBlocks.SMOOTH_STEEL_BLOCK);
		WARNING_BLOCK = block(WealizhModBlocks.WARNING_BLOCK);
		MIXED_DYE_BLACK_YELLOW = register("mixed_dye_black_yellow", MixedDyeBlackYellowItem::new);
		IRON_POWDER = register("iron_powder", IronPowderItem::new);
		COPPER_POWDER = register("copper_powder", CopperPowderItem::new);
		GOLD_POWDER = register("gold_powder", GoldPowderItem::new);
		STONE_POWDER = register("stone_powder", StonePowderItem::new);
		COAL_POWDER = register("coal_powder", CoalPowderItem::new);
		DIAMOND_POWDER = register("diamond_powder", DiamondPowderItem::new);
		EMERALD_POWDER = register("emerald_powder", EmeraldPowderItem::new);
		LAPIS_LAZULI_POWDER = register("lapis_lazuli_powder", LapisLazuliPowderItem::new);
		CHARCOAL_POWDER = register("charcoal_powder", CharcoalPowderItem::new);
		QUARTZ_POWDER = register("quartz_powder", QuartzPowderItem::new);
		AMETHYST_POWDER = register("amethyst_powder", AmethystPowderItem::new);
		SILVER_POWDER = register("silver_powder", SilverPowderItem::new);
		ZHEGNCOPPER_INGOT = register("zhegncopper_ingot", ZhegncopperIngotItem::new);
		RAW_ZHEGNCOPPER = register("raw_zhegncopper", RawZhegncopperItem::new);
		ZHEGNCOPPER_ORE = block(WealizhModBlocks.ZHEGNCOPPER_ORE);
		DEEPSLATE_ZHEGNCOPPER_ORE = block(WealizhModBlocks.DEEPSLATE_ZHEGNCOPPER_ORE);
		ZHEGNCOPPER_BLOCK = block(WealizhModBlocks.ZHEGNCOPPER_BLOCK);
		RAW_ZHEGNCOPPER_BLOCK = block(WealizhModBlocks.RAW_ZHEGNCOPPER_BLOCK);
		STECKED_STONE_ALLOY_POWDER = register("stecked_stone_alloy_powder", SteckedStoneAlloyPowderItem::new);
		STEEL_POWDER = register("steel_powder", SteelPowderItem::new);
		ZHEGNCOPPER_POWDER = register("zhegncopper_powder", ZhegncopperPowderItem::new);
		BRASS_INGOT = register("brass_ingot", BrassIngotItem::new);
		BRASS_POWDER = register("brass_powder", BrassPowderItem::new);
		BRASS_BLOCK = block(WealizhModBlocks.BRASS_BLOCK);
		BRASS_NUGGET = register("brass_nugget", BrassNuggetItem::new);
		LIGNITE = register("lignite", LigniteItem::new);
		LIGNITE_POWDER = register("lignite_powder", LignitePowderItem::new);
		LIGNITE_BLOCK = register("lignite_block", LigniteBlockBlock.Item::new);
		LIGNITE_ORE = block(WealizhModBlocks.LIGNITE_ORE);
		DEEPSLATE_LIGNITE_ORE = block(WealizhModBlocks.DEEPSLATE_LIGNITE_ORE);
		WAREHOUSE_BUCKET = block(WealizhModBlocks.WAREHOUSE_BUCKET);
		APPLE_WAREHOUSE_BUCKET = block(WealizhModBlocks.APPLE_WAREHOUSE_BUCKET);
		GOLDEN_APPLE_WAREHOUSE_BUCKET = block(WealizhModBlocks.GOLDEN_APPLE_WAREHOUSE_BUCKET);
		POTATO_WAREHOUSE_BUCKET = block(WealizhModBlocks.POTATO_WAREHOUSE_BUCKET);
		POISONOUS_POTATO_WAREHOUSE_BUCKET = block(WealizhModBlocks.POISONOUS_POTATO_WAREHOUSE_BUCKET);
		CARROT_WAREHOUSE_BUCKET = block(WealizhModBlocks.CARROT_WAREHOUSE_BUCKET);
		GOLDEN_CARROT_WAREHOUSE_BUCKET = block(WealizhModBlocks.GOLDEN_CARROT_WAREHOUSE_BUCKET);
		BEETROOT_WAREHOUSE_BUCKET = block(WealizhModBlocks.BEETROOT_WAREHOUSE_BUCKET);
		GLISTERING_MELON_SLICE_WAREHOUSE_BUCKET = block(WealizhModBlocks.GLISTERING_MELON_SLICE_WAREHOUSE_BUCKET);
		SWEET_BERRIES_WAREHOUSE_BUCKET = block(WealizhModBlocks.SWEET_BERRIES_WAREHOUSE_BUCKET);
		GLOW_BERRIES_WAREHOUSE_BUCKET = block(WealizhModBlocks.GLOW_BERRIES_WAREHOUSE_BUCKET);
		SUGAR_CANE_WAREHOUSE_BUCKET = block(WealizhModBlocks.SUGAR_CANE_WAREHOUSE_BUCKET);
		EGG_WAREHOUSE_BUCKET = block(WealizhModBlocks.EGG_WAREHOUSE_BUCKET);
		QUANTITATIVE_TRANSFORMATION_RECONSTRUCTOR = block(WealizhModBlocks.QUANTITATIVE_TRANSFORMATION_RECONSTRUCTOR);
		STEEL_PLATE = register("steel_plate", SteelPlateItem::new);
		QUANTITATIVE_TRANSFORMATION_SUBSTANCE_NUCLEUS = register("quantitative_transformation_substance_nucleus", QuantitativeTransformationSubstanceNucleusItem::new);
		COPPER_NUGGET = register("copper_nugget", CopperNuggetItem::new);
		COMBUSTION_CHAMBER = block(WealizhModBlocks.COMBUSTION_CHAMBER);
		SILVER_PICKAXE = register("silver_pickaxe", SilverPickaxeItem::new);
		SILVER_SWORD = register("silver_sword", SilverSwordItem::new);
		SILVER_AXE = register("silver_axe", SilverAxeItem::new);
		SILVER_SHOVEL = register("silver_shovel", SilverShovelItem::new);
		SILVER_HOE = register("silver_hoe", SilverHoeItem::new);
		ROCK_CRYSTAL = register("rock_crystal", RockCrystalItem::new);
		ROCK_CRYSTAL_POWDER = register("rock_crystal_powder", RockCrystalPowderItem::new);
		DEEPSLATE_ROCK_CRYSTAL_ORE = register("deepslate_rock_crystal_ore", DeepslateRockCrystalOreBlock.Item::new);
		ROCK_CRYSTAL_BLOCK = register("rock_crystal_block", RockCrystalBlockBlock.Item::new);
		HEAT_TRANSFER_PLATE = register("heat_transfer_plate", HeatTransferPlateItem::new);
		COPPER_THREAD = register("copper_thread", CopperThreadItem::new);
		THERMAL_ENERGY_POWER_GENERATION_PANEL = register("thermal_energy_power_generation_panel", ThermalEnergyPowerGenerationPanelBlock.Item::new);
		ALUMINUM_INGOT = register("aluminum_ingot", AluminumIngotItem::new);
		ALUMINUM_NUGGET = register("aluminum_nugget", AluminumNuggetItem::new);
		ALUMINUM_POWDER = register("aluminum_powder", AluminumPowderItem::new);
		ALUMINUM_PLATE = register("aluminum_plate", AluminumPlateItem::new);
		ALUMINUM_THREAD = register("aluminum_thread", AluminumThreadItem::new);
		IRON_THREAD = register("iron_thread", IronThreadItem::new);
		GOLD_THREAD = register("gold_thread", GoldThreadItem::new);
		SILVER_THREAD = register("silver_thread", SilverThreadItem::new);
		STEEL_THREAD = register("steel_thread", SteelThreadItem::new);
		GOLD_PLATE = register("gold_plate", GoldPlateItem::new);
		COPPER_PLATE = register("copper_plate", CopperPlateItem::new);
		BUTTON_BATTERY = register("button_battery", ButtonBatteryItem::new);
		ALUMINUM_STORAGE_BATTERY = block(WealizhModBlocks.ALUMINUM_STORAGE_BATTERY);
		ALUMINUM_BLOCK = block(WealizhModBlocks.ALUMINUM_BLOCK);
		ALUMINUM_ORE = block(WealizhModBlocks.ALUMINUM_ORE);
		DEEPSLATE_ALUMINUM_ORE = block(WealizhModBlocks.DEEPSLATE_ALUMINUM_ORE);
		RAW_ALUMINUM = register("raw_aluminum", RawAluminumItem::new);
		RAW_ALUMINUM_BLOCK = block(WealizhModBlocks.RAW_ALUMINUM_BLOCK);
		FLUID_TANK_LAVA = register("fluid_tank_lava", FluidTankLavaItem::new);
		LAVA = register("lava", LavaItem::new);
		CASING_THERMAL_ENERGY_POWER_GENERATION_PANEL = register("casing_thermal_energy_power_generation_panel", CasingThermalEnergyPowerGenerationPanelBlock.Item::new);
		HAND_INTERACTION = register("hand_interaction", HandInteractionItem::new);
		WRENCH = register("wrench", WrenchItem::new);
		CRASHER = register("crasher", properties -> new CrasherBlock.Item(properties.rarity(Rarity.EPIC)));
		PYRITE_CUBE = block(WealizhModBlocks.PYRITE_CUBE);
		PYRITE_POWDER = register("pyrite_powder", PyritePowderItem::new);
		PYRITE_BLOCK = block(WealizhModBlocks.PYRITE_BLOCK);
		PYRITE_ORE = block(WealizhModBlocks.PYRITE_ORE);
		DEEPSLATE_PYRITE_ORE = block(WealizhModBlocks.DEEPSLATE_PYRITE_ORE);
		EMPTY_BUTTON_BATTERY = register("empty_button_battery", EmptyButtonBatteryItem::new);
		ELECTRICITY = register("electricity", ElectricityItem::new);
		BATTERY = register("battery", BatteryItem::new);
		EMPTY_BATTERY = register("empty_battery", EmptyBatteryItem::new);
		PRAISE_FOR_THE_COMBUSTION_CHAMBER = register("praise_for_the_combustion_chamber", PraiseForTheCombustionChamberItem::new);
		STORAGE_BATTERY = block(WealizhModBlocks.STORAGE_BATTERY);
		COBALTIZED_GLASS = block(WealizhModBlocks.COBALTIZED_GLASS);
		COBALTIZED_SAND = block(WealizhModBlocks.COBALTIZED_SAND);
		TEMPERED_GLASS = block(WealizhModBlocks.TEMPERED_GLASS);
		COBALTIZED_GLASS_PANE = block(WealizhModBlocks.COBALTIZED_GLASS_PANE);
		TEMPERED_GLASS_PANE = block(WealizhModBlocks.TEMPERED_GLASS_PANE);
		FUEL_TANK_SOUL_FIRE_CATALYST = register("fuel_tank_soul_fire_catalyst", FuelTankSoulFireCatalystItem::new);
		INSULATION_HOSE = register("insulation_hose", InsulationHoseItem::new);
		INSULATION_BOARD = register("insulation_board", InsulationBoardItem::new);
		COPPER_CORE_BATTERY = register("copper_core_battery", CopperCoreBatteryItem::new);
		EMPTY_COPPER_CORE_BATTERY = register("empty_copper_core_battery", EmptyCopperCoreBatteryItem::new);
		INFINITE_BATTERY = register("infinite_battery", InfiniteBatteryItem::new);
		MIU_POLYMER_BLOCK = register("miu_polymer_block", MiuPolymerBlockBlock.Item::new);
		URANIUM_INGOT = register("uranium_ingot", UraniumIngotItem::new);
		RAW_URANIUM = register("raw_uranium", RawUraniumItem::new);
		URANIUM_POWDER = register("uranium_powder", UraniumPowderItem::new);
		INFINITE_STORAGE_BATTERY = block(WealizhModBlocks.INFINITE_STORAGE_BATTERY, new Item.Properties().rarity(Rarity.EPIC).fireResistant());
		URANIUM_BLOCK = register("uranium_block", UraniumBlockBlock.Item::new);
		RAW_URANIUM_BLOCK = register("raw_uranium_block", RawUraniumBlockBlock.Item::new);
		URANIUM_ORE = register("uranium_ore", UraniumOreBlock.Item::new);
		DEEPSLATE_URANIUM_ORE = register("deepslate_uranium_ore", DeepslateUraniumOreBlock.Item::new);
		ALUMINUM_COPPER_ALLOY_INGOT = register("aluminum_copper_alloy_ingot", AluminumCopperAlloyIngotItem::new);
		ALUMINUM_COPPER_ALLOY_POWDER = register("aluminum_copper_alloy_powder", AluminumCopperAlloyPowderItem::new);
		ALUMINUM_COPPER_ALLOY_PLATE = register("aluminum_copper_alloy_plate", AluminumCopperAlloyPlateItem::new);
		ALUMINUM_COPPER_ALLOY_BLOCK = block(WealizhModBlocks.ALUMINUM_COPPER_ALLOY_BLOCK);
		ALUMINUM_COPPER_ALLOY_BATTERY = register("aluminum_copper_alloy_battery", AluminumCopperAlloyBatteryItem::new);
		EMPTY_ALUMINUM_COPPER_ALLOY_BATTERY = register("empty_aluminum_copper_alloy_battery", EmptyAluminumCopperAlloyBatteryItem::new);
		ALUMINUM_COPPER_ALLOY_STORAGE_BATTERY = block(WealizhModBlocks.ALUMINUM_COPPER_ALLOY_STORAGE_BATTERY);
		HAND_CRANKED_GENERATOR = register("hand_cranked_generator", HandCrankedGeneratorBlock.Item::new);
		ROCKER = register("rocker", RockerItem::new);
		GLASS_FRAGMENTS = register("glass_fragments", GlassFragmentsItem::new);
		ASSEMBLY_TYPE_CONTROL_CONSOLE = block(WealizhModBlocks.ASSEMBLY_TYPE_CONTROL_CONSOLE);
		STEEL_BOX = block(WealizhModBlocks.STEEL_BOX);
		STEEL_PIPE = register("steel_pipe", SteelPipeItem::new);
		REBAR = register("rebar", RebarItem::new);
		LOW_LEVEL_CHIPS = register("low_level_chips", LowLevelChipsItem::new);
		COPPER_CABLE = register("copper_cable", CopperCableItem::new);
		YELLOW_CAKE = register("yellow_cake", YellowCakeItem::new);
		BOLT_IRON_BLOCK = block(WealizhModBlocks.BOLT_IRON_BLOCK);
		SHALE = block(WealizhModBlocks.SHALE);
		EXPOSURE_TO_RADIATION = register("exposure_to_radiation", ExposureToRadiationItem::new);
		DETONATOR = register("detonator", DetonatorItem::new);
		DETONATOR_BLOCK = block(WealizhModBlocks.DETONATOR_BLOCK);
		ASSEMBLY_ROOM = block(WealizhModBlocks.ASSEMBLY_ROOM);
		VOLTAGE_REGULATOR = register("voltage_regulator", VoltageRegulatorItem::new);
		POWER_BOOSTER_UNIT = register("power_booster_unit", PowerBoosterUnitItem::new);
		COMPONENT_HOUSING_GOLD = register("component_housing_gold", ComponentHousingGoldItem::new);
		CLOCK_COMPONENT = register("clock_component", ClockComponentItem::new);
		STEEL_FRAME = register("steel_frame", SteelFrameItem::new);
		STEEL_SHAFT = register("steel_shaft", SteelShaftItem::new);
		STRANGE_CLOCK = register("strange_clock", StrangeClockItem::new);
		GEAR = register("gear", GearItem::new);
		PEELING_SUGAR_CANE = register("peeling_sugar_cane", PeelingSugarCaneItem::new);
		SUGAR_CANE_RESIDUE = register("sugar_cane_residue", SugarCaneResidueItem::new);
		TRANSFORMATION = register("transformation", TransformationItem::new);
		EATING = register("eating", EatingItem::new);
		TOXIC = register("toxic", ToxicItem::new);
		COAL_DUST_LCON = register("coal_dust_lcon", CoalDustLconItem::new);
		RADIOACTIVITY = register("radioactivity", RadioactivityItem::new);
		RECTANGULAR_AND_SQUARE_SHAPED_PYRITE_LCON = register("rectangular_and_square_shaped_pyrite_lcon", RectangularAndSquareShapedPyriteLconItem::new);
		GRAPHITE = register("graphite", GraphiteItem::new);
		GRAPHITE_POWDER = register("graphite_powder", GraphitePowderItem::new);
		GRAPHITE_BLOCK = block(WealizhModBlocks.GRAPHITE_BLOCK);
		GRAPHITE_ORE = block(WealizhModBlocks.GRAPHITE_ORE);
		DEEPSLATE_GRAPHITE_ORE = block(WealizhModBlocks.DEEPSLATE_GRAPHITE_ORE);
		LEAD_INGOT = register("lead_ingot", LeadIngotItem::new);
		RAW_LEAD = register("raw_lead", RawLeadItem::new);
		LEAD_POWDER = register("lead_powder", LeadPowderItem::new);
		RAW_LEAD_BLOCK = register("raw_lead_block", RawLeadBlockBlock.Item::new);
		LEAD_ORE = register("lead_ore", LeadOreBlock.Item::new);
		DEEPSLATE_LEAD_ORE = register("deepslate_lead_ore", DeepslateLeadOreBlock.Item::new);
		GRAPHITELEAD_INGOT = register("graphitelead_ingot", GraphiteleadIngotItem::new);
		GRAPHITELEAD_POWDER = register("graphitelead_powder", GraphiteleadPowderItem::new);
		GRAPHITELEAD_PLATE = register("graphitelead_plate", GraphiteleadPlateItem::new);
		LEAD_PLATE = register("lead_plate", LeadPlateItem::new);
		GRAPHITELEAD_BLOCK = register("graphitelead_block", GraphiteleadBlockBlock.Item::new);
		LEAD_BLOCK = register("lead_block", LeadBlockBlock.Item::new);
		QUICKLY_SHUT_OFF_THE_ENGINE_LCON = register("quickly_shut_off_the_engine_lcon", QuicklyShutOffTheEngineLconItem::new);
		QUICKLY_SHUT_OFF_THE_ENGINE_BUT_IT_IS_THE_SOUL_VERSION_LCON = register("quickly_shut_off_the_engine_but_it_is_the_soul_version_lcon", QuicklyShutOffTheEngineButItIsTheSoulVersionLconItem::new);
		AN_APPLE_A_DAY_KEEPS_THE_DOCTOR_AWAY_LCON = register("an_apple_a_day_keeps_the_doctor_away_lcon", AnAppleADayKeepsTheDoctorAwayLconItem::new);
		SALT = register("salt", SaltItem::new);
		FLINT_POWDER = register("flint_powder", FlintPowderItem::new);
		FLINT_BLOCK = block(WealizhModBlocks.FLINT_BLOCK);
		GLASS_SHARDS = register("glass_shards", GlassShardsItem::new);
		SOAKING = register("soaking", SoakingItem::new);
		GEAR_ASSEMBLY = register("gear_assembly", GearAssemblyItem::new);
		SMALL_GEAR = register("small_gear", SmallGearItem::new);
		LINGUAN_COBALT = register("linguan_cobalt", LinguanCobaltItem::new);
		PEAT = register("peat", PeatItem::new);
		PEAT_BLOCK = block(WealizhModBlocks.PEAT_BLOCK);
		TURN_THE_CRANK_UNTIL_YOU_GET_TIRED_THEN_JUST_KEEP_ON_ENDURING_IT_ICON = register("turn_the_crank_until_you_get_tired_then_just_keep_on_enduring_it_icon", TurnTheCrankUntilYouGetTiredThenJustKeepOnEnduringItIconItem::new);
		KILN = register("kiln", KilnBlock.Item::new);
		SCHRODINGER = register("schrodinger", SchrodingerItem::new);
		SCHRODINGER_BLOCK = block(WealizhModBlocks.SCHRODINGER_BLOCK, new Item.Properties().rarity(Rarity.EPIC));
		BURN = register("burn", BurnItem::new);
		SOUL_BURN = register("soul_burn", SoulBurnItem::new);
		CRUSHER = block(WealizhModBlocks.CRUSHER);
		COMPOSITE_GUNPOWDER = register("composite_gunpowder", CompositeGunpowderItem::new);
		WIRING_LEAD = register("wiring_lead", WiringLeadItem::new);
		IRON_GEAR_BLADE = register("iron_gear_blade", IronGearBladeItem::new);
		COPPER_GEAR_BLADE = register("copper_gear_blade", CopperGearBladeItem::new);
		SILVER_GEAR_BLADE = register("silver_gear_blade", SilverGearBladeItem::new);
		STEEL_GEAR_BLADE = register("steel_gear_blade", SteelGearBladeItem::new);
		NETHERITE_POWDER = register("netherite_powder", NetheritePowderItem::new);
		NETHERITE_GEAR_BLADE = register("netherite_gear_blade", NetheriteGearBladeItem::new);
		NETHERITE_NUGGET = register("netherite_nugget", NetheriteNuggetItem::new);
		REDSTONE_CRYSTAL = register("redstone_crystal", RedstoneCrystalItem::new);
		RAW_REDSTONE_CRYSTAL = register("raw_redstone_crystal", RawRedstoneCrystalItem::new);
		RAW_REDSTONE_CRYSTAL_BLOCK = register("raw_redstone_crystal_block", RawRedstoneCrystalBlockBlock.Item::new);
		REDSTONE_CRYSTAL_BLOCK = block(WealizhModBlocks.REDSTONE_CRYSTAL_BLOCK);
		PRESSING_MACHINE = block(WealizhModBlocks.PRESSING_MACHINE);
		UNKNOWN = register("unknown", UnknownItem::new);
		PRESSING_STORAGE_ROOM = block(WealizhModBlocks.PRESSING_STORAGE_ROOM);
		RAW_REDSTONE = register("raw_redstone", RawRedstoneItem::new);
		RAW_REDSTONE_BLOCK = register("raw_redstone_block", RawRedstoneBlockBlock.Item::new);
		TYPE_ITEM = register("type_item", TypeItemItem::new);
		BY_PRODUCT = register("by_product", ByProductItem::new);
		STEEL_BILLETSMATERIAL = register("steel_billetsmaterial", SteelBilletsmaterialItem::new);
		POWDERED_BRAN_AND_MILLET_GRAINS_LCON = register("powdered_bran_and_millet_grains_lcon", PowderedBranAndMilletGrainsLconItem::new);
		SOLID_PLATE = register("solid_plate", SolidPlateItem::new);
		REDSTONE_WIRING_LEAD = register("redstone_wiring_lead", RedstoneWiringLeadItem::new);
		STEEL_SCAFFOLDING = block(WealizhModBlocks.STEEL_SCAFFOLDING);
		URANIUM_235_INGOT = register("uranium_235_ingot", Uranium235IngotItem::new);
		URANIUM_235_POWDER = register("uranium_235_powder", Uranium235PowderItem::new);
		URANIUM_235_BLOCK = register("uranium_235_block", Uranium235BlockBlock.Item::new);
		ZINC_INGOT = register("zinc_ingot", ZincIngotItem::new);
		ZINC_POWDER = register("zinc_powder", ZincPowderItem::new);
		ZINC_BLOCK = block(WealizhModBlocks.ZINC_BLOCK);
		ZINC_PLATE = register("zinc_plate", ZincPlateItem::new);
		RAW_ZINC = register("raw_zinc", RawZincItem::new);
		RAW_ZINC_BLOCK = block(WealizhModBlocks.RAW_ZINC_BLOCK);
		ZINC_ORE = block(WealizhModBlocks.ZINC_ORE);
		DEEPSLATE_ZINC_ORE = block(WealizhModBlocks.DEEPSLATE_ZINC_ORE);
		DECAY = register("decay", DecayItem::new);
		FUNBELITY = register("funbelity", FunbelityItem::new);
		FUNBELITY_POWDER = register("funbelity_powder", FunbelityPowderItem::new);
		COMPRESSED_FUNBELITY = register("compressed_funbelity", CompressedFunbelityItem::new);
		FUNBELITY_BLOCK = register("funbelity_block", FunbelityBlockBlock.Item::new);
		COMPRESSED_ALUMINUM_COPPER_ALLOY = register("compressed_aluminum_copper_alloy", CompressedAluminumCopperAlloyItem::new);
		FUNBELITY_CYTOSPLASM = register("funbelity_cytosplasm", FunbelityCytosplasmItem::new);
		COMPRESSOR = block(WealizhModBlocks.COMPRESSOR);
		COMPRESSION_CHAMBER = block(WealizhModBlocks.COMPRESSION_CHAMBER);
		STEEL_PISTON_GROUP = register("steel_piston_group", SteelPistonGroupItem::new);
		GOLD_CABLE = register("gold_cable", GoldCableItem::new);
		BRASS_CABLE = register("brass_cable", BrassCableItem::new);
		BRASS_THREAD = register("brass_thread", BrassThreadItem::new);
		PLACER = block(WealizhModBlocks.PLACER);
		IRON_BILLETSMATERIAL = register("iron_billetsmaterial", IronBilletsmaterialItem::new);
		DISCHARGE_BOX = block(WealizhModBlocks.DISCHARGE_BOX);
		EXPERIENCE_PARTICLE = register("experience_particle", ExperienceParticleItem::new);
		EXPERIENCE_NUGGET = register("experience_nugget", ExperienceNuggetItem::new);
		EXPERIENCE_CUBE_NUGGET = register("experience_cube_nugget", ExperienceCubeNuggetItem::new);
		EXPERIENCE_ABSORBER = register("experience_absorber", ExperienceAbsorberBlock.Item::new);
		EXPERIENCE_SOLID_CUBE = register("experience_solid_cube", ExperienceSolidCubeItem::new);
		EXPERIENCE_BLOCK = block(WealizhModBlocks.EXPERIENCE_BLOCK);
		SOLID_EXPERIENCE = register("solid_experience", SolidExperienceItem::new);
		EXPERIENCE_RELEASE_DEVICE = block(WealizhModBlocks.EXPERIENCE_RELEASE_DEVICE);
		REMOTE_STARTER = register("remote_starter", RemoteStarterItem::new);
		BUZZER = register("buzzer", BuzzerItem::new);
		NEUTRON_FISSION_GENERATOR_HONESILVER = register("neutron_fission_generator_honesilver", NeutronFissionGeneratorHonesilverItem::new);
		HONESILVER_BLOCK = block(WealizhModBlocks.HONESILVER_BLOCK);
		RAW_HONESILVER_BLOCK = block(WealizhModBlocks.RAW_HONESILVER_BLOCK);
		NETHER_HONESILVER_ORE = block(WealizhModBlocks.NETHER_HONESILVER_ORE);
		HONESILVER_INGOT = register("honesilver_ingot", HonesilverIngotItem::new);
		RAW_HONESILVER = register("raw_honesilver", RawHonesilverItem::new);
		HONESILVER_POWDER = register("honesilver_powder", HonesilverPowderItem::new);
		DIED_GRASS_BLOCK = block(WealizhModBlocks.DIED_GRASS_BLOCK);
		GEIGER_COUNTER = register("geiger_counter", GeigerCounterItem::new);
		GEIGER_TUBE = register("geiger_tube", GeigerTubeItem::new);
		DECAYED_LOG = block(WealizhModBlocks.DECAYED_LOG);
		CRACKED_BRICKS = block(WealizhModBlocks.CRACKED_BRICKS);
		CENTRIFUGE = block(WealizhModBlocks.CENTRIFUGE);
		CENTRIFUGE_AROUND_PIPE = block(WealizhModBlocks.CENTRIFUGE_AROUND_PIPE);
		GAS_TANK_HELIUM_GAS = register("gas_tank_helium_gas", GasTankHeliumGasItem::new);
		FUNBICOBALT_BLOCK = register("funbicobalt_block", FunbicobaltBlockBlock.Item::new);
		DECAYED_FUNBICOBALT_BLOCK = register("decayed_funbicobalt_block", DecayedFunbicobaltBlockBlock.Item::new);
		PURE_FUNBICOBALT_BLOCK = block(WealizhModBlocks.PURE_FUNBICOBALT_BLOCK);
		COBALT_BLOCK = block(WealizhModBlocks.COBALT_BLOCK);
		FUNBICOBALT = register("funbicobalt", FunbicobaltItem::new);
		DECAYED_FUNBICOBALT = register("decayed_funbicobalt", DecayedFunbicobaltItem::new);
		FUNBICOBALT_POWDER = register("funbicobalt_powder", FunbicobaltPowderItem::new);
		DECAYED_FUNBICOBALT_POWDER = register("decayed_funbicobalt_powder", DecayedFunbicobaltPowderItem::new);
		COBALT_INGOT = register("cobalt_ingot", CobaltIngotItem::new);
		COMPRESSED_FUNBICOBALT = register("compressed_funbicobalt", CompressedFunbicobaltItem::new);
		COMPRESSED_DECAYED_FUNBICOBALT = register("compressed_decayed_funbicobalt", CompressedDecayedFunbicobaltItem::new);
		PURE_FUNBICOBALT = register("pure_funbicobalt", PureFunbicobaltItem::new);
		PURE_FUNBICOBALT_POWDER = register("pure_funbicobalt_powder", PureFunbicobaltPowderItem::new);
		COBALT_POWDER = register("cobalt_powder", CobaltPowderItem::new);
		DEEPSLATE_FUNBICOBALT_ORE = block(WealizhModBlocks.DEEPSLATE_FUNBICOBALT_ORE);
		GERMINATION = block(WealizhModBlocks.GERMINATION);
		LANGUAGE_TESTER = register("language_tester", LanguageTesterItem::new);
		HUMUS = block(WealizhModBlocks.HUMUS);
		HUMUS_WAREHOUSE_BUCKET = block(WealizhModBlocks.HUMUS_WAREHOUSE_BUCKET);
		POLLUTION_SOURCE_SPAWN_EGG = register("pollution_source_spawn_egg", properties -> new SpawnEggItem(WealizhModEntities.POLLUTION_SOURCE.get(), properties));
		FUNBIELUMITUO = register("funbielumituo", FunbielumituoItem::new);
		FUNBIELUCURTUO = register("funbielucurtuo", FunbielucurtuoItem::new);
		LITYTIUM_INGOT = register("litytium_ingot", LitytiumIngotItem::new);
		LITYTIUM_POWDER = register("litytium_powder", LitytiumPowderItem::new);
		LITYTIUM_BLOCK = register("litytium_block", LitytiumBlockBlock.Item::new);
		HELIUM_GAS = register("helium_gas", HeliumGasItem::new);
		RED_COPPER_POWDER = register("red_copper_powder", RedCopperPowderItem::new);
		RED_COPPER_NUGGET = register("red_copper_nugget", RedCopperNuggetItem::new);
		RED_COPPER_THREAD = register("red_copper_thread", RedCopperThreadItem::new);
		RED_COPPER_CABLE = register("red_copper_cable", RedCopperCableItem::new);
		RED_COPPER_PLATE = register("red_copper_plate", RedCopperPlateItem::new);
		RED_COPPER_INGOT = register("red_copper_ingot", RedCopperIngotItem::new);
		RED_COPPER_BLOCK = block(WealizhModBlocks.RED_COPPER_BLOCK);
		COPPER_COIL = register("copper_coil", CopperCoilItem::new);
		RED_COPPER_COIL = register("red_copper_coil", RedCopperCoilItem::new);
		COPPER_STORAGE_BARREL = block(WealizhModBlocks.COPPER_STORAGE_BARREL);
		IRON_STORAGE_BARREL = block(WealizhModBlocks.IRON_STORAGE_BARREL);
		A_PINCH_PURE_FUNBICOBALT_POWDER = register("a_pinch_pure_funbicobalt_powder", APinchPureFunbicobaltPowderItem::new);
		A_PINCH_FUNBELITY_POWDER = register("a_pinch_funbelity_powder", APinchFunbelityPowderItem::new);
		A_PINCH_FUNBELITY_CYTOSPLASM = register("a_pinch_funbelity_cytosplasm", APinchFunbelityCytosplasmItem::new);
		ELECTRIC_MOTOR = register("electric_motor", ElectricMotorItem::new);
		URANIUM_HEXAFLUORIDE = register("uranium_hexafluoride", UraniumHexafluorideItem::new);
		GAS_TANK_URANIUM_HEXAFLUORIDE = register("gas_tank_uranium_hexafluoride", GasTankUraniumHexafluorideItem::new);
		FLUORINE_GAS = register("fluorine_gas", FluorineGasItem::new);
		GAS_TANK_FLUORINE_GAS = register("gas_tank_fluorine_gas", GasTankFluorineGasItem::new);
		CONCENTRATION_URANIUM_HEXAFLUORIDE = register("concentration_uranium_hexafluoride", ConcentrationUraniumHexafluorideItem::new);
		GAS_TANK_CONCENTRATION_URANIUM_HEXAFLUORIDE = register("gas_tank_concentration_uranium_hexafluoride", GasTankConcentrationUraniumHexafluorideItem::new);
		DEPLETED_URANIUM_HEXAFLUORIDE = register("depleted_uranium_hexafluoride", DepletedUraniumHexafluorideItem::new);
		GAS_TANK_DEPLETED_URANIUM_HEXAFLUORIDE = register("gas_tank_depleted_uranium_hexafluoride", GasTankDepletedUraniumHexafluorideItem::new);
		WIRE = block(WealizhModBlocks.WIRE);
		PIPE = block(WealizhModBlocks.PIPE);
		BARRELREVOLVING_WHEEL = register("barrelrevolving_wheel", BarrelrevolvingWheelItem::new);
		INFINITE_STORAGE_BARREL = block(WealizhModBlocks.INFINITE_STORAGE_BARREL);
		INFINITE_HOLD_STORAGE_TANK = register("infinite_hold_storage_tank", InfiniteHoldStorageTankItem::new);
		FIREPROOF_PAPER = register("fireproof_paper", FireproofPaperItem::new);
		GRASS_FIBERS = register("grass_fibers", GrassFibersItem::new);
		ROPE = register("rope", RopeItem::new);
		LAYER_COVERS_PLATE = register("layer_covers_plate", LayerCoversPlateItem::new);
		EMPTY = register("empty", EmptyItem::new);
		PLANNING_PAPER_ELECTRICITY_BAR = register("planning_paper_electricity_bar", PlanningPaperElectricityBarItem::new);
		CREATIVE_PLANNING_PAPER_NBT = register("creative_planning_paper_nbt", CreativePlanningPaperNBTItem::new);
		PLANNING_PAPER_EMPTY = register("planning_paper_empty", PlanningPaperEmptyItem::new);
		PLANNING_PAPER_LIQUID_PIPE = register("planning_paper_liquid_pipe", PlanningPaperLiquidPipeItem::new);
		CONCENTRATED_WIRE = block(WealizhModBlocks.CONCENTRATED_WIRE);
		CONCENTRATED_PIPE = block(WealizhModBlocks.CONCENTRATED_PIPE);
		UNIDIRECTIONAL_WIRE_VALVE = block(WealizhModBlocks.UNIDIRECTIONAL_WIRE_VALVE);
		UNIDIRECTIONAL_PIPE_VALVE = block(WealizhModBlocks.UNIDIRECTIONAL_PIPE_VALVE);
		MEOW_TITANIUM_INGOT = register("meow_titanium_ingot", MeowTitaniumIngotItem::new);
		TITANIUM_INGOT = register("titanium_ingot", TitaniumIngotItem::new);
		TITANIUM_POWDER = register("titanium_powder", TitaniumPowderItem::new);
		RAW_TITANIUM = register("raw_titanium", RawTitaniumItem::new);
		TITANIUM_BLOCK = block(WealizhModBlocks.TITANIUM_BLOCK);
		RAW_TITANIUM_BLOCK = block(WealizhModBlocks.RAW_TITANIUM_BLOCK);
		TITANIUM_ORE = block(WealizhModBlocks.TITANIUM_ORE);
		DEEPSLATE_TITANIUM_ORE = block(WealizhModBlocks.DEEPSLATE_TITANIUM_ORE);
		TITANIUM_NUGGET = register("titanium_nugget", TitaniumNuggetItem::new);
		TITANIUM_PLATE = register("titanium_plate", TitaniumPlateItem::new);
		HANZESH_CUBE_CRYSTAL = register("hanzesh_cube_crystal", HanzeshCubeCrystalItem::new);
		INDUSTRIAL_FURNACE_WALL = block(WealizhModBlocks.INDUSTRIAL_FURNACE_WALL);
		PETRIFIED_FORGING_TEMPLATE = register("petrified_forging_template", PetrifiedForgingTemplateItem::new);
		QUARTZ_ORE = block(WealizhModBlocks.QUARTZ_ORE);
		DEEPSTALE_QUARTZ_ORE = block(WealizhModBlocks.DEEPSTALE_QUARTZ_ORE);
		SULFUR_POWDER = register("sulfur_powder", SulfurPowderItem::new);
		SULFUR_ORE = block(WealizhModBlocks.SULFUR_ORE);
		DEEPSLATE_SULFUR_ORE = block(WealizhModBlocks.DEEPSLATE_SULFUR_ORE);
		SALTPETER = register("saltpeter", SaltpeterItem::new);
		SALTPETER_POWDER = register("saltpeter_powder", SaltpeterPowderItem::new);
		SALTPETER_BLOCK = block(WealizhModBlocks.SALTPETER_BLOCK);
		SALTPETER_ORE = block(WealizhModBlocks.SALTPETER_ORE);
		DEEPSLATE_SALTPETER_ORE = block(WealizhModBlocks.DEEPSLATE_SALTPETER_ORE);
		TITANIUM_STORAGE_BARREL = block(WealizhModBlocks.TITANIUM_STORAGE_BARREL);
		PLANNING_PAPER_CONCENTRATED_ASSIGN_PRIORITIES = register("planning_paper_concentrated_assign_priorities", PlanningPaperConcentratedAssignPrioritiesItem::new);
		NUCLEAR_BOMB = block(WealizhModBlocks.NUCLEAR_BOMB);
		URANIUM_FILLED_BOMB = block(WealizhModBlocks.URANIUM_FILLED_BOMB);
		A_PINCH_BRASS_POWDER = register("a_pinch_brass_powder", APinchBrassPowderItem::new);
		A_PINCH_HONESILVER_POWDER = register("a_pinch_honesilver_powder", APinchHonesilverPowderItem::new);
		URANIUM_235_NUGGET = register("uranium_235_nugget", Uranium235NuggetItem::new);
		URANIUM_235_BILLETSMATERIAL = register("uranium_235_billetsmaterial", Uranium235BilletsmaterialItem::new);
		CHARRED_STONE = block(WealizhModBlocks.CHARRED_STONE);
		PLANNING_PAPER_TRANSMISSION_VOLUME = register("planning_paper_transmission_volume", PlanningPaperTransmissionVolumeItem::new);
		ELECTRIC_LAMP = block(WealizhModBlocks.ELECTRIC_LAMP);
		ENCHANTED_GOLDEN_APPLE_WAREHOUSE_BUCKET = block(WealizhModBlocks.ENCHANTED_GOLDEN_APPLE_WAREHOUSE_BUCKET);
		CHARRED_STONE_SLAB = block(WealizhModBlocks.CHARRED_STONE_SLAB);
		CHARRED_STONE_STAIR = block(WealizhModBlocks.CHARRED_STONE_STAIR);
		CHARRED_STONE_WALL = block(WealizhModBlocks.CHARRED_STONE_WALL);
		CHARCOALIZED_LOG = block(WealizhModBlocks.CHARCOALIZED_LOG);
		CHARCOALIZED_PLANKS = block(WealizhModBlocks.CHARCOALIZED_PLANKS);
		CHARCOALIZED_PLANKS_SLAB = block(WealizhModBlocks.CHARCOALIZED_PLANKS_SLAB);
		CHARCOALIZED_PLANKS_STAIR = block(WealizhModBlocks.CHARCOALIZED_PLANKS_STAIR);
		CHARCOALIZED_PLANKS_FENCE = block(WealizhModBlocks.CHARCOALIZED_PLANKS_FENCE);
		CHARCOALIZED_PLANKS_FENCE_GATE = block(WealizhModBlocks.CHARCOALIZED_PLANKS_FENCE_GATE);
		LOGISTICS_PIPE = block(WealizhModBlocks.LOGISTICS_PIPE);
		CONCENTRATED_LOGISTICS_PIPE = block(WealizhModBlocks.CONCENTRATED_LOGISTICS_PIPE);
		ARGON_GAS = register("argon_gas", ArgonGasItem::new);
		GAS_TANK_ARGON_GAS = register("gas_tank_argon_gas", GasTankArgonGasItem::new);
		TUNGSTEN_INGOT = register("tungsten_ingot", TungstenIngotItem::new);
		TUNGSTEN_POWDER = register("tungsten_powder", TungstenPowderItem::new);
		TUNGSTEN_NUGGET = register("tungsten_nugget", TungstenNuggetItem::new);
		TUNGSTEN_PLATE = register("tungsten_plate", TungstenPlateItem::new);
		TUNGSTEN_THREAD = register("tungsten_thread", TungstenThreadItem::new);
		RAW_TUNGSTEN = register("raw_tungsten", RawTungstenItem::new);
		TUNGSTEN_BLOCK = block(WealizhModBlocks.TUNGSTEN_BLOCK, new Item.Properties().fireResistant());
		RAW_TUNGSTEN_BLOCK = block(WealizhModBlocks.RAW_TUNGSTEN_BLOCK, new Item.Properties().fireResistant());
		TUNGSTEN_ORE = block(WealizhModBlocks.TUNGSTEN_ORE);
		DEEPSLATE_TUNGSTEN_ORE = block(WealizhModBlocks.DEEPSLATE_TUNGSTEN_ORE);
		INCANDESCENT_LIGHT_BULB = register("incandescent_light_bulb", IncandescentLightBulbItem::new);
		ANEMENROUNZE = register("anemenrounze", AnemenrounzeItem::new);
		OXYGEN = register("oxygen", OxygenItem::new);
		GAS_TANK_OXYGEN = register("gas_tank_oxygen", GasTankOxygenItem::new);
		PLANNING_PAPER_REDSTONE_LOCK = register("planning_paper_redstone_lock", PlanningPaperRedstoneLockItem::new);
		TEMPORARY_BLOCK = block(WealizhModBlocks.TEMPORARY_BLOCK);
		CARBON_DIOXIDE = register("carbon_dioxide", CarbonDioxideItem::new);
		GAS_TANK_CARBON_DIOXIDE = register("gas_tank_carbon_dioxide", GasTankCarbonDioxideItem::new);
		NEON_GAS = register("neon_gas", NeonGasItem::new);
		GAS_TANK_NEON_GAS = register("gas_tank_neon_gas", GasTankNeonGasItem::new);
		FLUID_TANK_EMPTY = register("fluid_tank_empty", FluidTankEmptyItem::new);
		GAS_TANK_EMPTY = register("gas_tank_empty", GasTankEmptyItem::new);
		FUEL_TANK_EMPTY = register("fuel_tank_empty", FuelTankEmptyItem::new);
		NICKEL_INGOT = register("nickel_ingot", NickelIngotItem::new);
		NICKEL_NUGGET = register("nickel_nugget", NickelNuggetItem::new);
		RAW_NICKEL = register("raw_nickel", RawNickelItem::new);
		NICKEL_POWDER = register("nickel_powder", NickelPowderItem::new);
		NICKEL_BLOCK = block(WealizhModBlocks.NICKEL_BLOCK);
		RAW_NICKEL_BLOCK = block(WealizhModBlocks.RAW_NICKEL_BLOCK);
		NICKEL_ORE = block(WealizhModBlocks.NICKEL_ORE);
		DEEPSLATE_NICKEL_ORE = block(WealizhModBlocks.DEEPSLATE_NICKEL_ORE);
		NICKEL_THREAD = register("nickel_thread", NickelThreadItem::new);
		NAN_SUBSTANCE = block(WealizhModBlocks.NAN_SUBSTANCE);
		CHROMIUM_INGOT = register("chromium_ingot", ChromiumIngotItem::new);
		CHROMIUM_NUGGET = register("chromium_nugget", ChromiumNuggetItem::new);
		CHROMIUM_POWDER = register("chromium_powder", ChromiumPowderItem::new);
		CHROMIUM_THREAD = register("chromium_thread", ChromiumThreadItem::new);
		CHROMIUM_BLOCK = block(WealizhModBlocks.CHROMIUM_BLOCK);
		RAW_CHROMIUM_BLOCK = block(WealizhModBlocks.RAW_CHROMIUM_BLOCK);
		CHROMIUM_ORE = block(WealizhModBlocks.CHROMIUM_ORE);
		DEEPSLATE_CHROMIUM_ORE = block(WealizhModBlocks.DEEPSLATE_CHROMIUM_ORE);
		RAW_CHROMIUM = register("raw_chromium", RawChromiumItem::new);
		NICKEL_CHROMIUM_ALLOY_INGOT = register("nickel_chromium_alloy_ingot", NickelChromiumAlloyIngotItem::new);
		NICKEL_CHROMIUM_ALLOY_NUGGET = register("nickel_chromium_alloy_nugget", NickelChromiumAlloyNuggetItem::new);
		NICKEL_CHROMIUM_ALLOY_POWDER = register("nickel_chromium_alloy_powder", NickelChromiumAlloyPowderItem::new);
		NICKEL_CHROMIUM_ALLOY_THREAD = register("nickel_chromium_alloy_thread", NickelChromiumAlloyThreadItem::new);
		NICKEL_CHROMIUM_ALLOY_COIL = register("nickel_chromium_alloy_coil", NickelChromiumAlloyCoilItem::new);
		NICKEL_CHROMIUM_ALLOY_BLOCK = block(WealizhModBlocks.NICKEL_CHROMIUM_ALLOY_BLOCK);
		ELECTRIC_HEATER = block(WealizhModBlocks.ELECTRIC_HEATER);
		AIR_SEPARATOR = block(WealizhModBlocks.AIR_SEPARATOR);
		HYDROGEN = register("hydrogen", HydrogenItem::new);
		GAS_TANK_HYDROGEN = register("gas_tank_hydrogen", GasTankHydrogenItem::new);
		NITROGEN = register("nitrogen", NitrogenItem::new);
		GAS_TANK_NITROGEN = register("gas_tank_nitrogen", GasTankNitrogenItem::new);
		METHANE = register("methane", MethaneItem::new);
		GAS_TANK_METHANE = register("gas_tank_methane", GasTankMethaneItem::new);
		KRYPTON_GAS = register("krypton_gas", KryptonGasItem::new);
		GAS_TANK_KRYPTON_GAS = register("gas_tank_krypton_gas", GasTankKryptonGasItem::new);
		DINITROGEN_MONOXIDE = register("dinitrogen_monoxide", DinitrogenMonoxideItem::new);
		GAS_TANK_DINITROGEN_MONOXIDE = register("gas_tank_dinitrogen_monoxide", GasTankDinitrogenMonoxideItem::new);
		XENON_GAS = register("xenon_gas", XenonGasItem::new);
		GAS_TANK_XENON_GAS = register("gas_tank_xenon_gas", GasTankXenonGasItem::new);
		OZONE = register("ozone", OzoneItem::new);
		GAS_TANK_OZONE = register("gas_tank_ozone", GasTankOzoneItem::new);
		SLOT_OCCUPANCY_PLATE = register("slot_occupancy_plate", SlotOccupancyPlateItem::new);
		BLADE = register("blade", BladeItem::new);
		LUMP_SULFUR = register("lump_sulfur", LumpSulfurItem::new);
		SULFUR = block(WealizhModBlocks.SULFUR);
		LUMP_POTENT_SULFUR = register("lump_potent_sulfur", LumpPotentSulfurItem::new);
		POTENT_SULFUR_POWDER = register("potent_sulfur_powder", PotentSulfurPowderItem::new);
		POTENT_SULFUR = register("potent_sulfur", PotentSulfurBlock.Item::new);
		BRICK_CHIMNEY = block(WealizhModBlocks.BRICK_CHIMNEY);
		IRON_SLAB = block(WealizhModBlocks.IRON_SLAB);
		BRICK_CHIMNEY_OPENING = block(WealizhModBlocks.BRICK_CHIMNEY_OPENING);
		IRON_STAIR = block(WealizhModBlocks.IRON_STAIR);
		STEEL_SLAB = block(WealizhModBlocks.STEEL_SLAB);
		STEEL_STAIR = block(WealizhModBlocks.STEEL_STAIR);
		SMOOTH_STEEL_SLAB = block(WealizhModBlocks.SMOOTH_STEEL_SLAB);
		SMOOTH_STEEL_STAIR = block(WealizhModBlocks.SMOOTH_STEEL_STAIR);
		SMOOTH_IRON_BLOCK = block(WealizhModBlocks.SMOOTH_IRON_BLOCK);
		SMOOTH_IRON_STAIR = block(WealizhModBlocks.SMOOTH_IRON_STAIR);
		SMOOTH_IRON_SLAB = block(WealizhModBlocks.SMOOTH_IRON_SLAB);
		BOLT_IRON_STAIR = block(WealizhModBlocks.BOLT_IRON_STAIR);
		BOLT_IRON_SLAB = block(WealizhModBlocks.BOLT_IRON_SLAB);
		IRON_WALL = block(WealizhModBlocks.IRON_WALL);
		SMOOTH_IRON_WALL = block(WealizhModBlocks.SMOOTH_IRON_WALL);
		BOLT_IRON_WALL = block(WealizhModBlocks.BOLT_IRON_WALL);
		STEEL_WALL = block(WealizhModBlocks.STEEL_WALL);
		SMOOTH_STEEL_WALL = block(WealizhModBlocks.SMOOTH_STEEL_WALL);
		PRESSURE_MEASURING_PAPER_TUBE = block(WealizhModBlocks.PRESSURE_MEASURING_PAPER_TUBE);
		RADIOACTIVE_FALLOUT = register("radioactive_fallout", RadioactiveFalloutBlock.Item::new);
		THE_COLD_WINTER_ICON = register("the_cold_winter_icon", TheColdWinterIconItem::new);
		DIED_SHORT_GRASS = block(WealizhModBlocks.DIED_SHORT_GRASS);
		DIED_TALL_GRASS = block(WealizhModBlocks.DIED_TALL_GRASS);
		DIED_SHORT_GRASS_DESERT_DUST = block(WealizhModBlocks.DIED_SHORT_GRASS_DESERT_DUST);
		DIED_TALL_GRASS_DESERT_DUST = block(WealizhModBlocks.DIED_TALL_GRASS_DESERT_DUST);
		STEEL_BEAM = block(WealizhModBlocks.STEEL_BEAM);
		IRONL_SCAFFOLDING = block(WealizhModBlocks.IRONL_SCAFFOLDING);
		IRON_BEAM = block(WealizhModBlocks.IRON_BEAM);
		STUDIO_DOOR = doubleBlock(WealizhModBlocks.STUDIO_DOOR);
		OLD_STUDIO_DOOR = doubleBlock(WealizhModBlocks.OLD_STUDIO_DOOR);
		WAXED_STUDIO_DOOR = doubleBlock(WealizhModBlocks.WAXED_STUDIO_DOOR);
		MILK = register("milk", MilkItem::new);
		GLASS_BAFFLE_PLATE = block(WealizhModBlocks.GLASS_BAFFLE_PLATE);
		FLUID_TANK_MILK = register("fluid_tank_milk", FluidTankMilkItem::new);
		AMETHYST_BRICKS = block(WealizhModBlocks.AMETHYST_BRICKS);
		WHITE_CRYSTAL_SHARD = register("white_crystal_shard", WhiteCrystalShardItem::new);
		WHITE_CRYSTAL_POWDER = register("white_crystal_powder", WhiteCrystalPowderItem::new);
		WHITE_CRYSTAL_BLOCK = block(WealizhModBlocks.WHITE_CRYSTAL_BLOCK);
		BUDDING_WHITE_CRYSTAL = block(WealizhModBlocks.BUDDING_WHITE_CRYSTAL);
		SMALL_WHITE_CRYSTAL_BUD = block(WealizhModBlocks.SMALL_WHITE_CRYSTAL_BUD);
		MEDIUM_WHITE_CRYSTAL_BUD = block(WealizhModBlocks.MEDIUM_WHITE_CRYSTAL_BUD);
		LARGE_WHITE_CRYSTAL_BUD = block(WealizhModBlocks.LARGE_WHITE_CRYSTAL_BUD);
		WHITE_CRYSTAL_CLUSTER = block(WealizhModBlocks.WHITE_CRYSTAL_CLUSTER);
		WHITE_CRYSTAL_BRICKS = block(WealizhModBlocks.WHITE_CRYSTAL_BRICKS);
		CHARRED_BEDROCK = block(WealizhModBlocks.CHARRED_BEDROCK);
		MOLTEN_HIGH_TEMPERATURE_SOLIDIFIED_SUBSTANCE = block(WealizhModBlocks.MOLTEN_HIGH_TEMPERATURE_SOLIDIFIED_SUBSTANCE);
		MOLTEN_SAND_SOLIDIFICATION_SUBSTANCE = block(WealizhModBlocks.MOLTEN_SAND_SOLIDIFICATION_SUBSTANCE);
		TRINITITE = block(WealizhModBlocks.TRINITITE);
		TRINITITE_PANE = block(WealizhModBlocks.TRINITITE_PANE);
		DAWN_THE_TRUE_DAWN_ICON = register("dawn_the_true_dawn_icon", DawnTheTrueDawnIconItem::new);
	}

	// Start of user code block custom items
	// End of user code block custom items
	private static <I extends Item> DeferredItem<I> register(String name, Function<Item.Properties, ? extends I> supplier) {
		return REGISTRY.registerItem(name, supplier, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
		return block(block, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.registerItem(block.getId().getPath(), prop -> new BlockItem(block.get(), prop), properties);
	}

	private static DeferredItem<Item> doubleBlock(DeferredHolder<Block, Block> block) {
		return doubleBlock(block, new Item.Properties());
	}

	private static DeferredItem<Item> doubleBlock(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.registerItem(block.getId().getPath(), prop -> new DoubleHighBlockItem(block.get(), prop), properties);
	}

	@EventBusSubscriber(Dist.CLIENT)
	public static class ItemsClientSideHandler {
		@SubscribeEvent
		public static void registerItemModelProperties(RegisterRangeSelectItemModelPropertyEvent event) {
			event.register(ResourceLocation.parse("wealizh:infinite_hold_storage_tank/consumption_pattern"), InfiniteHoldStorageTankItem.ConsumptionPatternProperty.MAP_CODEC);
		}
	}
}