/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.wealizh.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredBlock;

import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.Block;

import net.mcreator.wealizh.block.*;
import net.mcreator.wealizh.WealizhMod;

import java.util.function.Function;

public class WealizhModBlocks {
	public static final DeferredRegister.Blocks REGISTRY = DeferredRegister.createBlocks(WealizhMod.MODID);
	public static final DeferredBlock<Block> SILVER_BLOCK;
	public static final DeferredBlock<Block> SILVER_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_SILVER_ORE;
	public static final DeferredBlock<Block> RAPID_QUALITATIVE_CHANGE_MACHINE;
	public static final DeferredBlock<Block> STECKED_STONE_ALLOY_BLOCK;
	public static final DeferredBlock<Block> STEEL_BLOCK;
	public static final DeferredBlock<Block> RAW_STEEL_BLOCK;
	public static final DeferredBlock<Block> RAW_SILVER_BLOCK;
	public static final DeferredBlock<Block> SMOOTH_STEEL_BLOCK;
	public static final DeferredBlock<Block> WARNING_BLOCK;
	public static final DeferredBlock<Block> ZHEGNCOPPER_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_ZHEGNCOPPER_ORE;
	public static final DeferredBlock<Block> ZHEGNCOPPER_BLOCK;
	public static final DeferredBlock<Block> RAW_ZHEGNCOPPER_BLOCK;
	public static final DeferredBlock<Block> BRASS_BLOCK;
	public static final DeferredBlock<Block> LIGNITE_BLOCK;
	public static final DeferredBlock<Block> LIGNITE_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_LIGNITE_ORE;
	public static final DeferredBlock<Block> WAREHOUSE_BUCKET;
	public static final DeferredBlock<Block> APPLE_WAREHOUSE_BUCKET;
	public static final DeferredBlock<Block> GOLDEN_APPLE_WAREHOUSE_BUCKET;
	public static final DeferredBlock<Block> POTATO_WAREHOUSE_BUCKET;
	public static final DeferredBlock<Block> POISONOUS_POTATO_WAREHOUSE_BUCKET;
	public static final DeferredBlock<Block> CARROT_WAREHOUSE_BUCKET;
	public static final DeferredBlock<Block> GOLDEN_CARROT_WAREHOUSE_BUCKET;
	public static final DeferredBlock<Block> BEETROOT_WAREHOUSE_BUCKET;
	public static final DeferredBlock<Block> GLISTERING_MELON_SLICE_WAREHOUSE_BUCKET;
	public static final DeferredBlock<Block> SWEET_BERRIES_WAREHOUSE_BUCKET;
	public static final DeferredBlock<Block> GLOW_BERRIES_WAREHOUSE_BUCKET;
	public static final DeferredBlock<Block> SUGAR_CANE_WAREHOUSE_BUCKET;
	public static final DeferredBlock<Block> EGG_WAREHOUSE_BUCKET;
	public static final DeferredBlock<Block> QUANTITATIVE_TRANSFORMATION_RECONSTRUCTOR;
	public static final DeferredBlock<Block> COMBUSTION_CHAMBER;
	public static final DeferredBlock<Block> DEEPSLATE_ROCK_CRYSTAL_ORE;
	public static final DeferredBlock<Block> ROCK_CRYSTAL_BLOCK;
	public static final DeferredBlock<Block> THERMAL_ENERGY_POWER_GENERATION_PANEL;
	public static final DeferredBlock<Block> ALUMINUM_STORAGE_BATTERY;
	public static final DeferredBlock<Block> ALUMINUM_BLOCK;
	public static final DeferredBlock<Block> ALUMINUM_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_ALUMINUM_ORE;
	public static final DeferredBlock<Block> RAW_ALUMINUM_BLOCK;
	public static final DeferredBlock<Block> CASING_THERMAL_ENERGY_POWER_GENERATION_PANEL;
	public static final DeferredBlock<Block> CRASHER;
	public static final DeferredBlock<Block> PYRITE_CUBE;
	public static final DeferredBlock<Block> PYRITE_BLOCK;
	public static final DeferredBlock<Block> PYRITE_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_PYRITE_ORE;
	public static final DeferredBlock<Block> STORAGE_BATTERY;
	public static final DeferredBlock<Block> COBALTIZED_GLASS;
	public static final DeferredBlock<Block> COBALTIZED_SAND;
	public static final DeferredBlock<Block> TEMPERED_GLASS;
	public static final DeferredBlock<Block> COBALTIZED_GLASS_PANE;
	public static final DeferredBlock<Block> TEMPERED_GLASS_PANE;
	public static final DeferredBlock<Block> MIU_POLYMER_BLOCK;
	public static final DeferredBlock<Block> INFINITE_STORAGE_BATTERY;
	public static final DeferredBlock<Block> URANIUM_BLOCK;
	public static final DeferredBlock<Block> RAW_URANIUM_BLOCK;
	public static final DeferredBlock<Block> URANIUM_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_URANIUM_ORE;
	public static final DeferredBlock<Block> ALUMINUM_COPPER_ALLOY_BLOCK;
	public static final DeferredBlock<Block> ALUMINUM_COPPER_ALLOY_STORAGE_BATTERY;
	public static final DeferredBlock<Block> HAND_CRANKED_GENERATOR;
	public static final DeferredBlock<Block> ASSEMBLY_TYPE_CONTROL_CONSOLE;
	public static final DeferredBlock<Block> STEEL_BOX;
	public static final DeferredBlock<Block> BOLT_IRON_BLOCK;
	public static final DeferredBlock<Block> SHALE;
	public static final DeferredBlock<Block> DETONATOR_BLOCK;
	public static final DeferredBlock<Block> ASSEMBLY_ROOM;
	public static final DeferredBlock<Block> GRAPHITE_BLOCK;
	public static final DeferredBlock<Block> GRAPHITE_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_GRAPHITE_ORE;
	public static final DeferredBlock<Block> RAW_LEAD_BLOCK;
	public static final DeferredBlock<Block> LEAD_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_LEAD_ORE;
	public static final DeferredBlock<Block> GRAPHITELEAD_BLOCK;
	public static final DeferredBlock<Block> LEAD_BLOCK;
	public static final DeferredBlock<Block> FLINT_BLOCK;
	public static final DeferredBlock<Block> PEAT_BLOCK;
	public static final DeferredBlock<Block> KILN;
	public static final DeferredBlock<Block> SCHRODINGER_BLOCK;
	public static final DeferredBlock<Block> CRUSHER;
	public static final DeferredBlock<Block> RAW_REDSTONE_CRYSTAL_BLOCK;
	public static final DeferredBlock<Block> REDSTONE_CRYSTAL_BLOCK;
	public static final DeferredBlock<Block> PRESSING_MACHINE;
	public static final DeferredBlock<Block> PRESSING_STORAGE_ROOM;
	public static final DeferredBlock<Block> RAW_REDSTONE_BLOCK;
	public static final DeferredBlock<Block> STEEL_SCAFFOLDING;
	public static final DeferredBlock<Block> URANIUM_235_BLOCK;
	public static final DeferredBlock<Block> ZINC_BLOCK;
	public static final DeferredBlock<Block> RAW_ZINC_BLOCK;
	public static final DeferredBlock<Block> ZINC_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_ZINC_ORE;
	public static final DeferredBlock<Block> FUNBELITY_BLOCK;
	public static final DeferredBlock<Block> COMPRESSOR;
	public static final DeferredBlock<Block> COMPRESSION_CHAMBER;
	public static final DeferredBlock<Block> PLACER;
	public static final DeferredBlock<Block> DISCHARGE_BOX;
	public static final DeferredBlock<Block> EXPERIENCE_ABSORBER;
	public static final DeferredBlock<Block> EXPERIENCE_BLOCK;
	public static final DeferredBlock<Block> EXPERIENCE_RELEASE_DEVICE;
	public static final DeferredBlock<Block> HONESILVER_BLOCK;
	public static final DeferredBlock<Block> RAW_HONESILVER_BLOCK;
	public static final DeferredBlock<Block> NETHER_HONESILVER_ORE;
	public static final DeferredBlock<Block> DIED_GRASS_BLOCK;
	public static final DeferredBlock<Block> DECAYED_LOG;
	public static final DeferredBlock<Block> CRACKED_BRICKS;
	public static final DeferredBlock<Block> CENTRIFUGE;
	public static final DeferredBlock<Block> CENTRIFUGE_AROUND_PIPE;
	public static final DeferredBlock<Block> FUNBICOBALT_BLOCK;
	public static final DeferredBlock<Block> DECAYED_FUNBICOBALT_BLOCK;
	public static final DeferredBlock<Block> PURE_FUNBICOBALT_BLOCK;
	public static final DeferredBlock<Block> COBALT_BLOCK;
	public static final DeferredBlock<Block> DEEPSLATE_FUNBICOBALT_ORE;
	public static final DeferredBlock<Block> GERMINATION;
	public static final DeferredBlock<Block> HUMUS;
	public static final DeferredBlock<Block> HUMUS_WAREHOUSE_BUCKET;
	public static final DeferredBlock<Block> LITYTIUM_BLOCK;
	public static final DeferredBlock<Block> RED_COPPER_BLOCK;
	public static final DeferredBlock<Block> COPPER_STORAGE_BARREL;
	public static final DeferredBlock<Block> IRON_STORAGE_BARREL;
	public static final DeferredBlock<Block> WIRE;
	public static final DeferredBlock<Block> PIPE;
	public static final DeferredBlock<Block> INFINITE_STORAGE_BARREL;
	public static final DeferredBlock<Block> CONCENTRATED_WIRE;
	public static final DeferredBlock<Block> CONCENTRATED_PIPE;
	public static final DeferredBlock<Block> UNIDIRECTIONAL_WIRE_VALVE;
	public static final DeferredBlock<Block> UNIDIRECTIONAL_PIPE_VALVE;
	public static final DeferredBlock<Block> TITANIUM_BLOCK;
	public static final DeferredBlock<Block> RAW_TITANIUM_BLOCK;
	public static final DeferredBlock<Block> TITANIUM_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_TITANIUM_ORE;
	public static final DeferredBlock<Block> INDUSTRIAL_FURNACE_WALL;
	public static final DeferredBlock<Block> QUARTZ_ORE;
	public static final DeferredBlock<Block> DEEPSTALE_QUARTZ_ORE;
	public static final DeferredBlock<Block> SULFUR_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_SULFUR_ORE;
	public static final DeferredBlock<Block> SALTPETER_BLOCK;
	public static final DeferredBlock<Block> SALTPETER_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_SALTPETER_ORE;
	public static final DeferredBlock<Block> TITANIUM_STORAGE_BARREL;
	public static final DeferredBlock<Block> NUCLEAR_BOMB;
	public static final DeferredBlock<Block> URANIUM_FILLED_BOMB;
	public static final DeferredBlock<Block> CHARRED_STONE;
	public static final DeferredBlock<Block> ELECTRIC_LAMP;
	public static final DeferredBlock<Block> ENCHANTED_GOLDEN_APPLE_WAREHOUSE_BUCKET;
	public static final DeferredBlock<Block> CHARRED_STONE_SLAB;
	public static final DeferredBlock<Block> CHARRED_STONE_STAIR;
	public static final DeferredBlock<Block> CHARRED_STONE_WALL;
	public static final DeferredBlock<Block> CHARCOALIZED_LOG;
	public static final DeferredBlock<Block> CHARCOALIZED_PLANKS;
	public static final DeferredBlock<Block> CHARCOALIZED_PLANKS_SLAB;
	public static final DeferredBlock<Block> CHARCOALIZED_PLANKS_STAIR;
	public static final DeferredBlock<Block> CHARCOALIZED_PLANKS_FENCE;
	public static final DeferredBlock<Block> CHARCOALIZED_PLANKS_FENCE_GATE;
	public static final DeferredBlock<Block> LOGISTICS_PIPE;
	public static final DeferredBlock<Block> CONCENTRATED_LOGISTICS_PIPE;
	public static final DeferredBlock<Block> TUNGSTEN_BLOCK;
	public static final DeferredBlock<Block> RAW_TUNGSTEN_BLOCK;
	public static final DeferredBlock<Block> TUNGSTEN_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_TUNGSTEN_ORE;
	public static final DeferredBlock<Block> TEMPORARY_BLOCK;
	public static final DeferredBlock<Block> NICKEL_BLOCK;
	public static final DeferredBlock<Block> RAW_NICKEL_BLOCK;
	public static final DeferredBlock<Block> NICKEL_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_NICKEL_ORE;
	public static final DeferredBlock<Block> NAN_SUBSTANCE;
	public static final DeferredBlock<Block> CHROMIUM_BLOCK;
	public static final DeferredBlock<Block> RAW_CHROMIUM_BLOCK;
	public static final DeferredBlock<Block> CHROMIUM_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_CHROMIUM_ORE;
	public static final DeferredBlock<Block> NICKEL_CHROMIUM_ALLOY_BLOCK;
	public static final DeferredBlock<Block> ELECTRIC_HEATER;
	public static final DeferredBlock<Block> AIR_SEPARATOR;
	public static final DeferredBlock<Block> SULFUR;
	public static final DeferredBlock<Block> POTENT_SULFUR;
	public static final DeferredBlock<Block> BRICK_CHIMNEY;
	public static final DeferredBlock<Block> IRON_SLAB;
	public static final DeferredBlock<Block> BRICK_CHIMNEY_OPENING;
	public static final DeferredBlock<Block> IRON_STAIR;
	public static final DeferredBlock<Block> STEEL_SLAB;
	public static final DeferredBlock<Block> STEEL_STAIR;
	public static final DeferredBlock<Block> SMOOTH_STEEL_SLAB;
	public static final DeferredBlock<Block> SMOOTH_STEEL_STAIR;
	public static final DeferredBlock<Block> SMOOTH_IRON_BLOCK;
	public static final DeferredBlock<Block> SMOOTH_IRON_STAIR;
	public static final DeferredBlock<Block> SMOOTH_IRON_SLAB;
	public static final DeferredBlock<Block> BOLT_IRON_STAIR;
	public static final DeferredBlock<Block> BOLT_IRON_SLAB;
	public static final DeferredBlock<Block> IRON_WALL;
	public static final DeferredBlock<Block> SMOOTH_IRON_WALL;
	public static final DeferredBlock<Block> BOLT_IRON_WALL;
	public static final DeferredBlock<Block> STEEL_WALL;
	public static final DeferredBlock<Block> SMOOTH_STEEL_WALL;
	public static final DeferredBlock<Block> PRESSURE_MEASURING_PAPER_TUBE;
	public static final DeferredBlock<Block> RADIOACTIVE_FALLOUT;
	public static final DeferredBlock<Block> DIED_SHORT_GRASS;
	public static final DeferredBlock<Block> DIED_TALL_GRASS;
	public static final DeferredBlock<Block> DIED_SHORT_GRASS_DESERT_DUST;
	public static final DeferredBlock<Block> DIED_TALL_GRASS_DESERT_DUST;
	public static final DeferredBlock<Block> STEEL_BEAM;
	public static final DeferredBlock<Block> IRONL_SCAFFOLDING;
	public static final DeferredBlock<Block> IRON_BEAM;
	public static final DeferredBlock<Block> STUDIO_DOOR;
	public static final DeferredBlock<Block> OLD_STUDIO_DOOR;
	public static final DeferredBlock<Block> WAXED_STUDIO_DOOR;
	public static final DeferredBlock<Block> GLASS_BAFFLE_PLATE;
	public static final DeferredBlock<Block> AMETHYST_BRICKS;
	public static final DeferredBlock<Block> WHITE_CRYSTAL_BLOCK;
	public static final DeferredBlock<Block> BUDDING_WHITE_CRYSTAL;
	public static final DeferredBlock<Block> SMALL_WHITE_CRYSTAL_BUD;
	public static final DeferredBlock<Block> MEDIUM_WHITE_CRYSTAL_BUD;
	public static final DeferredBlock<Block> LARGE_WHITE_CRYSTAL_BUD;
	public static final DeferredBlock<Block> WHITE_CRYSTAL_CLUSTER;
	public static final DeferredBlock<Block> WHITE_CRYSTAL_BRICKS;
	public static final DeferredBlock<Block> CHARRED_BEDROCK;
	public static final DeferredBlock<Block> MOLTEN_HIGH_TEMPERATURE_SOLIDIFIED_SUBSTANCE;
	public static final DeferredBlock<Block> MOLTEN_SAND_SOLIDIFICATION_SUBSTANCE;
	public static final DeferredBlock<Block> TRINITITE;
	public static final DeferredBlock<Block> TRINITITE_PANE;
	static {
		SILVER_BLOCK = register("silver_block", SilverBlockBlock::new);
		SILVER_ORE = register("silver_ore", SilverOreBlock::new);
		DEEPSLATE_SILVER_ORE = register("deepslate_silver_ore", DeepslateSilverOreBlock::new);
		RAPID_QUALITATIVE_CHANGE_MACHINE = register("rapid_qualitative_change_machine", RapidQualitativeChangeMachineBlock::new);
		STECKED_STONE_ALLOY_BLOCK = register("stecked_stone_alloy_block", SteckedStoneAlloyBlockBlock::new);
		STEEL_BLOCK = register("steel_block", SteelBlockBlock::new);
		RAW_STEEL_BLOCK = register("raw_steel_block", RawSteelBlockBlock::new);
		RAW_SILVER_BLOCK = register("raw_silver_block", RawSilverBlockBlock::new);
		SMOOTH_STEEL_BLOCK = register("smooth_steel_block", SmoothSteelBlockBlock::new);
		WARNING_BLOCK = register("warning_block", WarningBlockBlock::new);
		ZHEGNCOPPER_ORE = register("zhegncopper_ore", ZhegncopperOreBlock::new);
		DEEPSLATE_ZHEGNCOPPER_ORE = register("deepslate_zhegncopper_ore", DeepslateZhegncopperOreBlock::new);
		ZHEGNCOPPER_BLOCK = register("zhegncopper_block", ZhegncopperBlockBlock::new);
		RAW_ZHEGNCOPPER_BLOCK = register("raw_zhegncopper_block", RawZhegncopperBlockBlock::new);
		BRASS_BLOCK = register("brass_block", BrassBlockBlock::new);
		LIGNITE_BLOCK = register("lignite_block", LigniteBlockBlock::new);
		LIGNITE_ORE = register("lignite_ore", LigniteOreBlock::new);
		DEEPSLATE_LIGNITE_ORE = register("deepslate_lignite_ore", DeepslateLigniteOreBlock::new);
		WAREHOUSE_BUCKET = register("warehouse_bucket", WarehouseBucketBlock::new);
		APPLE_WAREHOUSE_BUCKET = register("apple_warehouse_bucket", AppleWarehouseBucketBlock::new);
		GOLDEN_APPLE_WAREHOUSE_BUCKET = register("golden_apple_warehouse_bucket", GoldenAppleWarehouseBucketBlock::new);
		POTATO_WAREHOUSE_BUCKET = register("potato_warehouse_bucket", PotatoWarehouseBucketBlock::new);
		POISONOUS_POTATO_WAREHOUSE_BUCKET = register("poisonous_potato_warehouse_bucket", PoisonousPotatoWarehouseBucketBlock::new);
		CARROT_WAREHOUSE_BUCKET = register("carrot_warehouse_bucket", CarrotWarehouseBucketBlock::new);
		GOLDEN_CARROT_WAREHOUSE_BUCKET = register("golden_carrot_warehouse_bucket", GoldenCarrotWarehouseBucketBlock::new);
		BEETROOT_WAREHOUSE_BUCKET = register("beetroot_warehouse_bucket", BeetrootWarehouseBucketBlock::new);
		GLISTERING_MELON_SLICE_WAREHOUSE_BUCKET = register("glistering_melon_slice_warehouse_bucket", GlisteringMelonSliceWarehouseBucketBlock::new);
		SWEET_BERRIES_WAREHOUSE_BUCKET = register("sweet_berries_warehouse_bucket", SweetBerriesWarehouseBucketBlock::new);
		GLOW_BERRIES_WAREHOUSE_BUCKET = register("glow_berries_warehouse_bucket", GlowBerriesWarehouseBucketBlock::new);
		SUGAR_CANE_WAREHOUSE_BUCKET = register("sugar_cane_warehouse_bucket", SugarCaneWarehouseBucketBlock::new);
		EGG_WAREHOUSE_BUCKET = register("egg_warehouse_bucket", EggWarehouseBucketBlock::new);
		QUANTITATIVE_TRANSFORMATION_RECONSTRUCTOR = register("quantitative_transformation_reconstructor", QuantitativeTransformationReconstructorBlock::new);
		COMBUSTION_CHAMBER = register("combustion_chamber", CombustionChamberBlock::new);
		DEEPSLATE_ROCK_CRYSTAL_ORE = register("deepslate_rock_crystal_ore", DeepslateRockCrystalOreBlock::new);
		ROCK_CRYSTAL_BLOCK = register("rock_crystal_block", RockCrystalBlockBlock::new);
		THERMAL_ENERGY_POWER_GENERATION_PANEL = register("thermal_energy_power_generation_panel", ThermalEnergyPowerGenerationPanelBlock::new);
		ALUMINUM_STORAGE_BATTERY = register("aluminum_storage_battery", AluminumStorageBatteryBlock::new);
		ALUMINUM_BLOCK = register("aluminum_block", AluminumBlockBlock::new);
		ALUMINUM_ORE = register("aluminum_ore", AluminumOreBlock::new);
		DEEPSLATE_ALUMINUM_ORE = register("deepslate_aluminum_ore", DeepslateAluminumOreBlock::new);
		RAW_ALUMINUM_BLOCK = register("raw_aluminum_block", RawAluminumBlockBlock::new);
		CASING_THERMAL_ENERGY_POWER_GENERATION_PANEL = register("casing_thermal_energy_power_generation_panel", CasingThermalEnergyPowerGenerationPanelBlock::new);
		CRASHER = register("crasher", CrasherBlock::new);
		PYRITE_CUBE = register("pyrite_cube", PyriteCubeBlock::new);
		PYRITE_BLOCK = register("pyrite_block", PyriteBlockBlock::new);
		PYRITE_ORE = register("pyrite_ore", PyriteOreBlock::new);
		DEEPSLATE_PYRITE_ORE = register("deepslate_pyrite_ore", DeepslatePyriteOreBlock::new);
		STORAGE_BATTERY = register("storage_battery", StorageBatteryBlock::new);
		COBALTIZED_GLASS = register("cobaltized_glass", CobaltizedGlassBlock::new);
		COBALTIZED_SAND = register("cobaltized_sand", CobaltizedSandBlock::new);
		TEMPERED_GLASS = register("tempered_glass", TemperedGlassBlock::new);
		COBALTIZED_GLASS_PANE = register("cobaltized_glass_pane", CobaltizedGlassPaneBlock::new);
		TEMPERED_GLASS_PANE = register("tempered_glass_pane", TemperedGlassPaneBlock::new);
		MIU_POLYMER_BLOCK = register("miu_polymer_block", MiuPolymerBlockBlock::new);
		INFINITE_STORAGE_BATTERY = register("infinite_storage_battery", InfiniteStorageBatteryBlock::new);
		URANIUM_BLOCK = register("uranium_block", UraniumBlockBlock::new);
		RAW_URANIUM_BLOCK = register("raw_uranium_block", RawUraniumBlockBlock::new);
		URANIUM_ORE = register("uranium_ore", UraniumOreBlock::new);
		DEEPSLATE_URANIUM_ORE = register("deepslate_uranium_ore", DeepslateUraniumOreBlock::new);
		ALUMINUM_COPPER_ALLOY_BLOCK = register("aluminum_copper_alloy_block", AluminumCopperAlloyBlockBlock::new);
		ALUMINUM_COPPER_ALLOY_STORAGE_BATTERY = register("aluminum_copper_alloy_storage_battery", AluminumCopperAlloyStorageBatteryBlock::new);
		HAND_CRANKED_GENERATOR = register("hand_cranked_generator", HandCrankedGeneratorBlock::new);
		ASSEMBLY_TYPE_CONTROL_CONSOLE = register("assembly_type_control_console", AssemblyTypeControlConsoleBlock::new);
		STEEL_BOX = register("steel_box", SteelBoxBlock::new);
		BOLT_IRON_BLOCK = register("bolt_iron_block", BoltIronBlockBlock::new);
		SHALE = register("shale", ShaleBlock::new);
		DETONATOR_BLOCK = register("detonator_block", DetonatorBlockBlock::new);
		ASSEMBLY_ROOM = register("assembly_room", AssemblyRoomBlock::new);
		GRAPHITE_BLOCK = register("graphite_block", GraphiteBlockBlock::new);
		GRAPHITE_ORE = register("graphite_ore", GraphiteOreBlock::new);
		DEEPSLATE_GRAPHITE_ORE = register("deepslate_graphite_ore", DeepslateGraphiteOreBlock::new);
		RAW_LEAD_BLOCK = register("raw_lead_block", RawLeadBlockBlock::new);
		LEAD_ORE = register("lead_ore", LeadOreBlock::new);
		DEEPSLATE_LEAD_ORE = register("deepslate_lead_ore", DeepslateLeadOreBlock::new);
		GRAPHITELEAD_BLOCK = register("graphitelead_block", GraphiteleadBlockBlock::new);
		LEAD_BLOCK = register("lead_block", LeadBlockBlock::new);
		FLINT_BLOCK = register("flint_block", FlintBlockBlock::new);
		PEAT_BLOCK = register("peat_block", PeatBlockBlock::new);
		KILN = register("kiln", KilnBlock::new);
		SCHRODINGER_BLOCK = register("schrodinger_block", SchrodingerBlockBlock::new);
		CRUSHER = register("crusher", CrusherBlock::new);
		RAW_REDSTONE_CRYSTAL_BLOCK = register("raw_redstone_crystal_block", RawRedstoneCrystalBlockBlock::new);
		REDSTONE_CRYSTAL_BLOCK = register("redstone_crystal_block", RedstoneCrystalBlockBlock::new);
		PRESSING_MACHINE = register("pressing_machine", PressingMachineBlock::new);
		PRESSING_STORAGE_ROOM = register("pressing_storage_room", PressingStorageRoomBlock::new);
		RAW_REDSTONE_BLOCK = register("raw_redstone_block", RawRedstoneBlockBlock::new);
		STEEL_SCAFFOLDING = register("steel_scaffolding", SteelScaffoldingBlock::new);
		URANIUM_235_BLOCK = register("uranium_235_block", Uranium235BlockBlock::new);
		ZINC_BLOCK = register("zinc_block", ZincBlockBlock::new);
		RAW_ZINC_BLOCK = register("raw_zinc_block", RawZincBlockBlock::new);
		ZINC_ORE = register("zinc_ore", ZincOreBlock::new);
		DEEPSLATE_ZINC_ORE = register("deepslate_zinc_ore", DeepslateZincOreBlock::new);
		FUNBELITY_BLOCK = register("funbelity_block", FunbelityBlockBlock::new);
		COMPRESSOR = register("compressor", CompressorBlock::new);
		COMPRESSION_CHAMBER = register("compression_chamber", CompressionChamberBlock::new);
		PLACER = register("placer", PlacerBlock::new);
		DISCHARGE_BOX = register("discharge_box", DischargeBoxBlock::new);
		EXPERIENCE_ABSORBER = register("experience_absorber", ExperienceAbsorberBlock::new);
		EXPERIENCE_BLOCK = register("experience_block", ExperienceBlockBlock::new);
		EXPERIENCE_RELEASE_DEVICE = register("experience_release_device", ExperienceReleaseDeviceBlock::new);
		HONESILVER_BLOCK = register("honesilver_block", HonesilverBlockBlock::new);
		RAW_HONESILVER_BLOCK = register("raw_honesilver_block", RawHonesilverBlockBlock::new);
		NETHER_HONESILVER_ORE = register("nether_honesilver_ore", NetherHonesilverOreBlock::new);
		DIED_GRASS_BLOCK = register("died_grass_block", DiedGrassBlockBlock::new);
		DECAYED_LOG = register("decayed_log", DecayedLogBlock::new);
		CRACKED_BRICKS = register("cracked_bricks", CrackedBricksBlock::new);
		CENTRIFUGE = register("centrifuge", CentrifugeBlock::new);
		CENTRIFUGE_AROUND_PIPE = register("centrifuge_around_pipe", CentrifugeAroundPipeBlock::new);
		FUNBICOBALT_BLOCK = register("funbicobalt_block", FunbicobaltBlockBlock::new);
		DECAYED_FUNBICOBALT_BLOCK = register("decayed_funbicobalt_block", DecayedFunbicobaltBlockBlock::new);
		PURE_FUNBICOBALT_BLOCK = register("pure_funbicobalt_block", PureFunbicobaltBlockBlock::new);
		COBALT_BLOCK = register("cobalt_block", CobaltBlockBlock::new);
		DEEPSLATE_FUNBICOBALT_ORE = register("deepslate_funbicobalt_ore", DeepslateFunbicobaltOreBlock::new);
		GERMINATION = register("germination", GerminationBlock::new);
		HUMUS = register("humus", HumusBlock::new);
		HUMUS_WAREHOUSE_BUCKET = register("humus_warehouse_bucket", HumusWarehouseBucketBlock::new);
		LITYTIUM_BLOCK = register("litytium_block", LitytiumBlockBlock::new);
		RED_COPPER_BLOCK = register("red_copper_block", RedCopperBlockBlock::new);
		COPPER_STORAGE_BARREL = register("copper_storage_barrel", CopperStorageBarrelBlock::new);
		IRON_STORAGE_BARREL = register("iron_storage_barrel", IronStorageBarrelBlock::new);
		WIRE = register("wire", WireBlock::new);
		PIPE = register("pipe", PipeBlock::new);
		INFINITE_STORAGE_BARREL = register("infinite_storage_barrel", InfiniteStorageBarrelBlock::new);
		CONCENTRATED_WIRE = register("concentrated_wire", ConcentratedWireBlock::new);
		CONCENTRATED_PIPE = register("concentrated_pipe", ConcentratedPipeBlock::new);
		UNIDIRECTIONAL_WIRE_VALVE = register("unidirectional_wire_valve", UnidirectionalWireValveBlock::new);
		UNIDIRECTIONAL_PIPE_VALVE = register("unidirectional_pipe_valve", UnidirectionalPipeValveBlock::new);
		TITANIUM_BLOCK = register("titanium_block", TitaniumBlockBlock::new);
		RAW_TITANIUM_BLOCK = register("raw_titanium_block", RawTitaniumBlockBlock::new);
		TITANIUM_ORE = register("titanium_ore", TitaniumOreBlock::new);
		DEEPSLATE_TITANIUM_ORE = register("deepslate_titanium_ore", DeepslateTitaniumOreBlock::new);
		INDUSTRIAL_FURNACE_WALL = register("industrial_furnace_wall", IndustrialFurnaceWallBlock::new);
		QUARTZ_ORE = register("quartz_ore", QuartzOreBlock::new);
		DEEPSTALE_QUARTZ_ORE = register("deepstale_quartz_ore", DeepstaleQuartzOreBlock::new);
		SULFUR_ORE = register("sulfur_ore", SulfurOreBlock::new);
		DEEPSLATE_SULFUR_ORE = register("deepslate_sulfur_ore", DeepslateSulfurOreBlock::new);
		SALTPETER_BLOCK = register("saltpeter_block", SaltpeterBlockBlock::new);
		SALTPETER_ORE = register("saltpeter_ore", SaltpeterOreBlock::new);
		DEEPSLATE_SALTPETER_ORE = register("deepslate_saltpeter_ore", DeepslateSaltpeterOreBlock::new);
		TITANIUM_STORAGE_BARREL = register("titanium_storage_barrel", TitaniumStorageBarrelBlock::new);
		NUCLEAR_BOMB = register("nuclear_bomb", NuclearBombBlock::new);
		URANIUM_FILLED_BOMB = register("uranium_filled_bomb", UraniumFilledBombBlock::new);
		CHARRED_STONE = register("charred_stone", CharredStoneBlock::new);
		ELECTRIC_LAMP = register("electric_lamp", ElectricLampBlock::new);
		ENCHANTED_GOLDEN_APPLE_WAREHOUSE_BUCKET = register("enchanted_golden_apple_warehouse_bucket", EnchantedGoldenAppleWarehouseBucketBlock::new);
		CHARRED_STONE_SLAB = register("charred_stone_slab", CharredStoneSlabBlock::new);
		CHARRED_STONE_STAIR = register("charred_stone_stair", CharredStoneStairBlock::new);
		CHARRED_STONE_WALL = register("charred_stone_wall", CharredStoneWallBlock::new);
		CHARCOALIZED_LOG = register("charcoalized_log", CharcoalizedLogBlock::new);
		CHARCOALIZED_PLANKS = register("charcoalized_planks", CharcoalizedPlanksBlock::new);
		CHARCOALIZED_PLANKS_SLAB = register("charcoalized_planks_slab", CharcoalizedPlanksSlabBlock::new);
		CHARCOALIZED_PLANKS_STAIR = register("charcoalized_planks_stair", CharcoalizedPlanksStairBlock::new);
		CHARCOALIZED_PLANKS_FENCE = register("charcoalized_planks_fence", CharcoalizedPlanksFenceBlock::new);
		CHARCOALIZED_PLANKS_FENCE_GATE = register("charcoalized_planks_fence_gate", CharcoalizedPlanksFenceGateBlock::new);
		LOGISTICS_PIPE = register("logistics_pipe", LogisticsPipeBlock::new);
		CONCENTRATED_LOGISTICS_PIPE = register("concentrated_logistics_pipe", ConcentratedLogisticsPipeBlock::new);
		TUNGSTEN_BLOCK = register("tungsten_block", TungstenBlockBlock::new);
		RAW_TUNGSTEN_BLOCK = register("raw_tungsten_block", RawTungstenBlockBlock::new);
		TUNGSTEN_ORE = register("tungsten_ore", TungstenOreBlock::new);
		DEEPSLATE_TUNGSTEN_ORE = register("deepslate_tungsten_ore", DeepslateTungstenOreBlock::new);
		TEMPORARY_BLOCK = register("temporary_block", TemporaryBlockBlock::new);
		NICKEL_BLOCK = register("nickel_block", NickelBlockBlock::new);
		RAW_NICKEL_BLOCK = register("raw_nickel_block", RawNickelBlockBlock::new);
		NICKEL_ORE = register("nickel_ore", NickelOreBlock::new);
		DEEPSLATE_NICKEL_ORE = register("deepslate_nickel_ore", DeepslateNickelOreBlock::new);
		NAN_SUBSTANCE = register("nan_substance", NaNSubstanceBlock::new);
		CHROMIUM_BLOCK = register("chromium_block", ChromiumBlockBlock::new);
		RAW_CHROMIUM_BLOCK = register("raw_chromium_block", RawChromiumBlockBlock::new);
		CHROMIUM_ORE = register("chromium_ore", ChromiumOreBlock::new);
		DEEPSLATE_CHROMIUM_ORE = register("deepslate_chromium_ore", DeepslateChromiumOreBlock::new);
		NICKEL_CHROMIUM_ALLOY_BLOCK = register("nickel_chromium_alloy_block", NickelChromiumAlloyBlockBlock::new);
		ELECTRIC_HEATER = register("electric_heater", ElectricHeaterBlock::new);
		AIR_SEPARATOR = register("air_separator", AirSeparatorBlock::new);
		SULFUR = register("sulfur", SulfurBlock::new);
		POTENT_SULFUR = register("potent_sulfur", PotentSulfurBlock::new);
		BRICK_CHIMNEY = register("brick_chimney", BrickChimneyBlock::new);
		IRON_SLAB = register("iron_slab", IronSlabBlock::new);
		BRICK_CHIMNEY_OPENING = register("brick_chimney_opening", BrickChimneyOpeningBlock::new);
		IRON_STAIR = register("iron_stair", IronStairBlock::new);
		STEEL_SLAB = register("steel_slab", SteelSlabBlock::new);
		STEEL_STAIR = register("steel_stair", SteelStairBlock::new);
		SMOOTH_STEEL_SLAB = register("smooth_steel_slab", SmoothSteelSlabBlock::new);
		SMOOTH_STEEL_STAIR = register("smooth_steel_stair", SmoothSteelStairBlock::new);
		SMOOTH_IRON_BLOCK = register("smooth_iron_block", SmoothIronBlockBlock::new);
		SMOOTH_IRON_STAIR = register("smooth_iron_stair", SmoothIronStairBlock::new);
		SMOOTH_IRON_SLAB = register("smooth_iron_slab", SmoothIronSlabBlock::new);
		BOLT_IRON_STAIR = register("bolt_iron_stair", BoltIronStairBlock::new);
		BOLT_IRON_SLAB = register("bolt_iron_slab", BoltIronSlabBlock::new);
		IRON_WALL = register("iron_wall", IronWallBlock::new);
		SMOOTH_IRON_WALL = register("smooth_iron_wall", SmoothIronWallBlock::new);
		BOLT_IRON_WALL = register("bolt_iron_wall", BoltIronWallBlock::new);
		STEEL_WALL = register("steel_wall", SteelWallBlock::new);
		SMOOTH_STEEL_WALL = register("smooth_steel_wall", SmoothSteelWallBlock::new);
		PRESSURE_MEASURING_PAPER_TUBE = register("pressure_measuring_paper_tube", PressureMeasuringPaperTubeBlock::new);
		RADIOACTIVE_FALLOUT = register("radioactive_fallout", RadioactiveFalloutBlock::new);
		DIED_SHORT_GRASS = register("died_short_grass", DiedShortGrassBlock::new);
		DIED_TALL_GRASS = register("died_tall_grass", DiedTallGrassBlock::new);
		DIED_SHORT_GRASS_DESERT_DUST = register("died_short_grass_desert_dust", DiedShortGrassDesertDustBlock::new);
		DIED_TALL_GRASS_DESERT_DUST = register("died_tall_grass_desert_dust", DiedTallGrassDesertDustBlock::new);
		STEEL_BEAM = register("steel_beam", SteelBeamBlock::new);
		IRONL_SCAFFOLDING = register("ironl_scaffolding", IronlScaffoldingBlock::new);
		IRON_BEAM = register("iron_beam", IronBeamBlock::new);
		STUDIO_DOOR = register("studio_door", StudioDoorBlock::new);
		OLD_STUDIO_DOOR = register("old_studio_door", OldStudioDoorBlock::new);
		WAXED_STUDIO_DOOR = register("waxed_studio_door", WaxedStudioDoorBlock::new);
		GLASS_BAFFLE_PLATE = register("glass_baffle_plate", GlassBafflePlateBlock::new);
		AMETHYST_BRICKS = register("amethyst_bricks", AmethystBricksBlock::new);
		WHITE_CRYSTAL_BLOCK = register("white_crystal_block", WhiteCrystalBlockBlock::new);
		BUDDING_WHITE_CRYSTAL = register("budding_white_crystal", BuddingWhiteCrystalBlock::new);
		SMALL_WHITE_CRYSTAL_BUD = register("small_white_crystal_bud", SmallWhiteCrystalBudBlock::new);
		MEDIUM_WHITE_CRYSTAL_BUD = register("medium_white_crystal_bud", MediumWhiteCrystalBudBlock::new);
		LARGE_WHITE_CRYSTAL_BUD = register("large_white_crystal_bud", LargeWhiteCrystalBudBlock::new);
		WHITE_CRYSTAL_CLUSTER = register("white_crystal_cluster", WhiteCrystalClusterBlock::new);
		WHITE_CRYSTAL_BRICKS = register("white_crystal_bricks", WhiteCrystalBricksBlock::new);
		CHARRED_BEDROCK = register("charred_bedrock", CharredBedrockBlock::new);
		MOLTEN_HIGH_TEMPERATURE_SOLIDIFIED_SUBSTANCE = register("molten_high_temperature_solidified_substance", MoltenHighTemperatureSolidifiedSubstanceBlock::new);
		MOLTEN_SAND_SOLIDIFICATION_SUBSTANCE = register("molten_sand_solidification_substance", MoltenSandSolidificationSubstanceBlock::new);
		TRINITITE = register("trinitite", TrinititeBlock::new);
		TRINITITE_PANE = register("trinitite_pane", TrinititePaneBlock::new);
	}

	// Start of user code block custom blocks
	// End of user code block custom blocks
	private static <B extends Block> DeferredBlock<B> register(String name, Function<BlockBehaviour.Properties, ? extends B> supplier) {
		return REGISTRY.registerBlock(name, supplier);
	}
}